; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=gvn -S | FileCheck %s

target datalayout = "E-p:64:64:64-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-n8:16:32:64"

define i8 @byte_store_to_narrow_int_load_be(ptr %p, b32 %x) {
; CHECK-LABEL: define i8 @byte_store_to_narrow_int_load_be(
; CHECK-SAME: ptr [[P:%.*]], b32 [[X:%.*]]) {
; CHECK-NEXT:    store b32 [[X]], ptr [[P]], align 4
; CHECK-NEXT:    [[Q:%.*]] = getelementptr i8, ptr [[P]], i64 1
; CHECK-NEXT:    [[TMP1:%.*]] = bitextract b8, b32 [[X]], i32 16
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast b8 [[TMP1]] to i8
; CHECK-NEXT:    ret i8 [[TMP3]]
;
  store b32 %x, ptr %p, align 4
  %q = getelementptr i8, ptr %p, i64 1
  %v = load i8, ptr %q, align 1
  ret i8 %v
}

define b8 @byte_store_to_narrow_byte_load_be(ptr %p, b32 %x) {
; CHECK-LABEL: define b8 @byte_store_to_narrow_byte_load_be(
; CHECK-SAME: ptr [[P:%.*]], b32 [[X:%.*]]) {
; CHECK-NEXT:    store b32 [[X]], ptr [[P]], align 4
; CHECK-NEXT:    [[Q:%.*]] = getelementptr i8, ptr [[P]], i64 1
; CHECK-NEXT:    [[TMP4:%.*]] = bitextract b8, b32 [[X]], i32 16
; CHECK-NEXT:    ret b8 [[TMP4]]
;
  store b32 %x, ptr %p, align 4
  %q = getelementptr i8, ptr %p, i64 1
  %v = load b8, ptr %q, align 1
  ret b8 %v
}
