; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=gvn -S | FileCheck %s

target datalayout = "e-p:64:64:64-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-n8:16:32:64"

define i8 @byte_store_to_narrow_int_load(ptr %p, b32 %x) {
; CHECK-LABEL: define i8 @byte_store_to_narrow_int_load(
; CHECK-SAME: ptr [[P:%.*]], b32 [[X:%.*]]) {
; CHECK-NEXT:    store b32 [[X]], ptr [[P]], align 4
; CHECK-NEXT:    [[Q:%.*]] = getelementptr i8, ptr [[P]], i64 1
; CHECK-NEXT:    [[TMP1:%.*]] = bitextract b8, b32 [[X]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast b8 [[TMP1]] to i8
; CHECK-NEXT:    ret i8 [[TMP3]]
;
  store b32 %x, ptr %p, align 4
  %q = getelementptr i8, ptr %p, i64 1
  %v = load i8, ptr %q, align 1
  ret i8 %v
}

define b8 @byte_store_to_narrow_byte_load(ptr %p, b32 %x) {
; CHECK-LABEL: define b8 @byte_store_to_narrow_byte_load(
; CHECK-SAME: ptr [[P:%.*]], b32 [[X:%.*]]) {
; CHECK-NEXT:    store b32 [[X]], ptr [[P]], align 4
; CHECK-NEXT:    [[Q:%.*]] = getelementptr i8, ptr [[P]], i64 1
; CHECK-NEXT:    [[TMP4:%.*]] = bitextract b8, b32 [[X]], i32 8
; CHECK-NEXT:    ret b8 [[TMP4]]
;
  store b32 %x, ptr %p, align 4
  %q = getelementptr i8, ptr %p, i64 1
  %v = load b8, ptr %q, align 1
  ret b8 %v
}

define b32 @byte_store_to_same_width_load(ptr %p, b32 %x) {
; CHECK-LABEL: define b32 @byte_store_to_same_width_load(
; CHECK-SAME: ptr [[P:%.*]], b32 [[X:%.*]]) {
; CHECK-NEXT:    store b32 [[X]], ptr [[P]], align 4
; CHECK-NEXT:    ret b32 [[X]]
;
  store b32 %x, ptr %p, align 4
  %v = load b32, ptr %p, align 4
  ret b32 %v
}

define i16 @byte_store_to_int_load_offset0(ptr %p, b32 %x) {
; CHECK-LABEL: define i16 @byte_store_to_int_load_offset0(
; CHECK-SAME: ptr [[P:%.*]], b32 [[X:%.*]]) {
; CHECK-NEXT:    store b32 [[X]], ptr [[P]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = bitextract b16, b32 [[X]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast b16 [[TMP1]] to i16
; CHECK-NEXT:    ret i16 [[TMP2]]
;
  store b32 %x, ptr %p, align 4
  %v = load i16, ptr %p, align 2
  ret i16 %v
}
