; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=sroa -S | FileCheck %s

target datalayout = "e-p:64:64:64-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-n8:16:32:64"

define i8 @bytetoint(b8 %x) {
; CHECK-LABEL: define i8 @bytetoint(
; CHECK-SAME: b8 [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast b8 [[X]] to i8
; CHECK-NEXT:    ret i8 [[TMP1]]
;
  %a = alloca b8, align 1
  store b8 %x, ptr %a, align 1
  %v = load i8, ptr %a, align 1
  ret i8 %v
}

define ptr @bytetoptr(b64 %x) {
; CHECK-LABEL: define ptr @bytetoptr(
; CHECK-SAME: b64 [[X:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = alloca b64, align 8
; CHECK-NEXT:    store b64 [[X]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[A]], align 8
; CHECK-NEXT:    ret ptr [[TMP1]]
;
  %a = alloca b64, align 8
  store b64 %x, ptr %a, align 8
  %v = load ptr, ptr %a, align 8
  ret ptr %v
}

define float @bytetofloat(b32 %x) {
; CHECK-LABEL: define float @bytetofloat(
; CHECK-SAME: b32 [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast b32 [[X]] to float
; CHECK-NEXT:    ret float [[TMP1]]
;
  %a = alloca b32, align 4
  store b32 %x, ptr %a, align 4
  %v = load float, ptr %a, align 4
  ret float %v
}

define i8 @extract_int_from_byte(b32 %x) {
; CHECK-LABEL: define i8 @extract_int_from_byte(
; CHECK-SAME: b32 [[X:%.*]]) {
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast b32 [[X]] to i32
; CHECK-NEXT:    [[A_2_EXTRACT_SHIFT:%.*]] = lshr i32 [[TMP2]], 16
; CHECK-NEXT:    [[TMP1:%.*]] = trunc i32 [[A_2_EXTRACT_SHIFT]] to i8
; CHECK-NEXT:    ret i8 [[TMP1]]
;
  %a = alloca b32, align 4
  store b32 %x, ptr %a, align 4
  %p = getelementptr i8, ptr %a, i64 2
  %v = load i8, ptr %p, align 1
  ret i8 %v
}

define b8 @extract_byte_from_byte(b32 %x) {
; CHECK-LABEL: define b8 @extract_byte_from_byte(
; CHECK-SAME: b32 [[X:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = alloca b32, align 4
; CHECK-NEXT:    store b32 [[X]], ptr [[A]], align 4
; CHECK-NEXT:    [[A_2_P_SROA_IDX:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 2
; CHECK-NEXT:    [[EXTRACT:%.*]] = load b8, ptr [[A_2_P_SROA_IDX]], align 2
; CHECK-NEXT:    ret b8 [[EXTRACT]]
;
  %a = alloca b32, align 4
  store b32 %x, ptr %a, align 4
  %p = getelementptr i8, ptr %a, i64 2
  %v = load b8, ptr %p, align 1
  ret b8 %v
}

define b32 @insert_int_into_byte(b32 %old, i8 %x) {
; CHECK-LABEL: define b32 @insert_int_into_byte(
; CHECK-SAME: b32 [[OLD:%.*]], i8 [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast b32 [[OLD]] to i32
; CHECK-NEXT:    [[A_2_INSERT_EXT:%.*]] = zext i8 [[X]] to i32
; CHECK-NEXT:    [[A_2_INSERT_SHIFT:%.*]] = shl i32 [[A_2_INSERT_EXT]], 16
; CHECK-NEXT:    [[A_2_INSERT_MASK:%.*]] = and i32 [[TMP1]], -16711681
; CHECK-NEXT:    [[A_2_INSERT_INSERT:%.*]] = or i32 [[A_2_INSERT_MASK]], [[A_2_INSERT_SHIFT]]
; CHECK-NEXT:    [[INSERT:%.*]] = bitcast i32 [[A_2_INSERT_INSERT]] to b32
; CHECK-NEXT:    ret b32 [[INSERT]]
;
  %a = alloca b32, align 4
  store b32 %old, ptr %a, align 4
  %p = getelementptr i8, ptr %a, i64 2
  store i8 %x, ptr %p, align 1
  %v = load b32, ptr %a, align 4
  ret b32 %v
}

define b32 @insert_byte_into_byte(b32 %old, b8 %x) {
; CHECK-LABEL: define b32 @insert_byte_into_byte(
; CHECK-SAME: b32 [[OLD:%.*]], b8 [[X:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = alloca b32, align 4
; CHECK-NEXT:    store b32 [[OLD]], ptr [[A]], align 4
; CHECK-NEXT:    [[A_2_P_SROA_IDX:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 2
; CHECK-NEXT:    store b8 [[X]], ptr [[A_2_P_SROA_IDX]], align 2
; CHECK-NEXT:    [[INSERT:%.*]] = load b32, ptr [[A]], align 4
; CHECK-NEXT:    ret b32 [[INSERT]]
;
  %a = alloca b32, align 4
  store b32 %old, ptr %a, align 4
  %p = getelementptr i8, ptr %a, i64 2
  store b8 %x, ptr %p, align 1
  %v = load b32, ptr %a, align 4
  ret b32 %v
}

define b32 @inttobyte(i32 %x) {
; CHECK-LABEL: define b32 @inttobyte(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast i32 [[X]] to b32
; CHECK-NEXT:    ret b32 [[TMP1]]
;
  %a = alloca i32, align 4
  store i32 %x, ptr %a, align 4
  %v = load b32, ptr %a, align 4
  ret b32 %v
}

define b32 @floattobyte(float %x) {
; CHECK-LABEL: define b32 @floattobyte(
; CHECK-SAME: float [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast float [[X]] to b32
; CHECK-NEXT:    ret b32 [[TMP1]]
;
  %a = alloca float, align 4
  store float %x, ptr %a, align 4
  %v = load b32, ptr %a, align 4
  ret b32 %v
}

define b64 @ptrtobyte(ptr %x) {
; CHECK-LABEL: define b64 @ptrtobyte(
; CHECK-SAME: ptr [[X:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[X]], ptr [[A]], align 8
; CHECK-NEXT:    [[A_0_V:%.*]] = load b64, ptr [[A]], align 8
; CHECK-NEXT:    ret b64 [[A_0_V]]
;
  %a = alloca ptr, align 8
  store ptr %x, ptr %a, align 8
  %v = load b64, ptr %a, align 8
  ret b64 %v
}

; The byte slices are not a multiple of a byte in size, so integer widening is
; not viable and the alloca is not promoted.
define b8 @sub_byte_width_not_widenable(b1 %x, b1 %y) {
; CHECK-LABEL: define b8 @sub_byte_width_not_widenable(
; CHECK-SAME: b1 [[X:%.*]], b1 [[Y:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = alloca b8, align 1
; CHECK-NEXT:    store b1 [[X]], ptr [[A]], align 1
; CHECK-NEXT:    [[A_0_V:%.*]] = load b8, ptr [[A]], align 1
; CHECK-NEXT:    ret b8 [[A_0_V]]
;
  %a = alloca b8, align 1
  store b1 %x, ptr %a, align 1
  %p = getelementptr i8, ptr %a, i64 1
  store b1 %y, ptr %p, align 1
  %v = load b8, ptr %a, align 1
  ret b8 %v
}

; Byte types of different widths cannot be converted into one another, but a
; smaller byte can still be extracted from a larger one.
define b16 @byte_width_mismatch(b32 %x) {
; CHECK-LABEL: define b16 @byte_width_mismatch(
; CHECK-SAME: b32 [[X:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = alloca b32, align 4
; CHECK-NEXT:    store b32 [[X]], ptr [[A]], align 4
; CHECK-NEXT:    [[A_0_V:%.*]] = load b16, ptr [[A]], align 4
; CHECK-NEXT:    ret b16 [[A_0_V]]
;
  %a = alloca b32, align 4
  store b32 %x, ptr %a, align 4
  %v = load b16, ptr %a, align 2
  ret b16 %v
}
