; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=sroa -S | FileCheck %s

target datalayout = "E-p:64:64:64-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-n8:16:32:64"

define i8 @extract_int_from_byte_be(b32 %x) {
; CHECK-LABEL: define i8 @extract_int_from_byte_be(
; CHECK-SAME: b32 [[X:%.*]]) {
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast b32 [[X]] to i32
; CHECK-NEXT:    [[A_2_EXTRACT_SHIFT:%.*]] = lshr i32 [[TMP2]], 8
; CHECK-NEXT:    [[TMP1:%.*]] = trunc i32 [[A_2_EXTRACT_SHIFT]] to i8
; CHECK-NEXT:    ret i8 [[TMP1]]
;
  %a = alloca b32, align 4
  store b32 %x, ptr %a, align 4
  %p = getelementptr i8, ptr %a, i64 2
  %v = load i8, ptr %p, align 1
  ret i8 %v
}

define b32 @insert_byte_into_byte_be(b32 %old, b8 %x) {
; CHECK-LABEL: define b32 @insert_byte_into_byte_be(
; CHECK-SAME: b32 [[OLD:%.*]], b8 [[X:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = alloca b32, align 4
; CHECK-NEXT:    store b32 [[OLD]], ptr [[A]], align 4
; CHECK-NEXT:    [[A_2_P_SROA_IDX:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 2
; CHECK-NEXT:    store b8 [[X]], ptr [[A_2_P_SROA_IDX]], align 2
; CHECK-NEXT:    [[INSERT:%.*]] = load b32, ptr [[A]], align 4
; CHECK-NEXT:    ret b32 [[INSERT]]
;
  %a = alloca b32, align 4
  store b32 %old, ptr %a, align 4
  %p = getelementptr i8, ptr %a, i64 2
  store b8 %x, ptr %p, align 1
  %v = load b32, ptr %a, align 4
  ret b32 %v
}

define b8 @extract_byte_from_byte_be(b32 %x) {
; CHECK-LABEL: define b8 @extract_byte_from_byte_be(
; CHECK-SAME: b32 [[X:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = alloca b32, align 4
; CHECK-NEXT:    store b32 [[X]], ptr [[A]], align 4
; CHECK-NEXT:    [[A_2_P_SROA_IDX:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 2
; CHECK-NEXT:    [[A_2_V:%.*]] = load b8, ptr [[A_2_P_SROA_IDX]], align 2
; CHECK-NEXT:    ret b8 [[A_2_V]]
;
  %a = alloca b32, align 4
  store b32 %x, ptr %a, align 4
  %p = getelementptr i8, ptr %a, i64 2
  %v = load b8, ptr %p, align 1
  ret b8 %v
}

define b32 @insert_int_into_byte_be(b32 %old, i8 %x) {
; CHECK-LABEL: define b32 @insert_int_into_byte_be(
; CHECK-SAME: b32 [[OLD:%.*]], i8 [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast b32 [[OLD]] to i32
; CHECK-NEXT:    [[A_2_INSERT_EXT:%.*]] = zext i8 [[X]] to i32
; CHECK-NEXT:    [[A_2_INSERT_SHIFT:%.*]] = shl i32 [[A_2_INSERT_EXT]], 8
; CHECK-NEXT:    [[A_2_INSERT_MASK:%.*]] = and i32 [[TMP1]], -65281
; CHECK-NEXT:    [[A_2_INSERT_INSERT:%.*]] = or i32 [[A_2_INSERT_MASK]], [[A_2_INSERT_SHIFT]]
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast i32 [[A_2_INSERT_INSERT]] to b32
; CHECK-NEXT:    ret b32 [[TMP2]]
;
  %a = alloca b32, align 4
  store b32 %old, ptr %a, align 4
  %p = getelementptr i8, ptr %a, i64 2
  store i8 %x, ptr %p, align 1
  %v = load b32, ptr %a, align 4
  ret b32 %v
}

define i8 @bytetoint_be(b8 %x) {
; CHECK-LABEL: define i8 @bytetoint_be(
; CHECK-SAME: b8 [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast b8 [[X]] to i8
; CHECK-NEXT:    ret i8 [[TMP1]]
;
  %a = alloca b8, align 1
  store b8 %x, ptr %a, align 1
  %v = load i8, ptr %a, align 1
  ret i8 %v
}

define ptr @bytetoptr_be(b64 %x) {
; CHECK-LABEL: define ptr @bytetoptr_be(
; CHECK-SAME: b64 [[X:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = alloca b64, align 8
; CHECK-NEXT:    store b64 [[X]], ptr [[A]], align 8
; CHECK-NEXT:    [[A_0_V:%.*]] = load ptr, ptr [[A]], align 8
; CHECK-NEXT:    ret ptr [[A_0_V]]
;
  %a = alloca b64, align 8
  store b64 %x, ptr %a, align 8
  %v = load ptr, ptr %a, align 8
  ret ptr %v
}

define float @bytetofloat_be(b32 %x) {
; CHECK-LABEL: define float @bytetofloat_be(
; CHECK-SAME: b32 [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast b32 [[X]] to float
; CHECK-NEXT:    ret float [[TMP1]]
;
  %a = alloca b32, align 4
  store b32 %x, ptr %a, align 4
  %v = load float, ptr %a, align 4
  ret float %v
}
