; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -aa-pipeline=basic-aa -passes=slp-vectorizer < %s -mtriple=x86_64-unknown -S | FileCheck %s --check-prefixes=SSE2
; RUN: opt -aa-pipeline=basic-aa -passes=slp-vectorizer < %s -mtriple=x86_64-unknown -mcpu=slm -S | FileCheck %s --check-prefixes=SLM
; RUN: opt -aa-pipeline=basic-aa -passes=slp-vectorizer < %s -mtriple=x86_64-unknown -mcpu=corei7-avx -S | FileCheck %s --check-prefixes=AVX
; RUN: opt -aa-pipeline=basic-aa -passes=slp-vectorizer < %s -mtriple=x86_64-unknown -mcpu=core-avx2 -S | FileCheck %s --check-prefixes=AVX
; RUN: opt -aa-pipeline=basic-aa -passes=slp-vectorizer < %s -mtriple=x86_64-unknown -mcpu=knl -S | FileCheck %s --check-prefixes=AVX
; RUN: opt -aa-pipeline=basic-aa -passes=slp-vectorizer < %s -mtriple=x86_64-unknown -mcpu=skx -mattr=+avx512bw -S | FileCheck %s --check-prefixes=AVX

define <2 x i64> @load_bytecast_ext(ptr %p0) {
; SSE2-LABEL: @load_bytecast_ext(
; SSE2-NEXT:    [[TMP1:%.*]] = load <2 x b8>, ptr [[P0:%.*]], align 1
; SSE2-NEXT:    [[TMP2:%.*]] = bytecast <2 x b8> [[TMP1]] to <2 x i8>
; SSE2-NEXT:    [[TMP3:%.*]] = zext <2 x i8> [[TMP2]] to <2 x i64>
; SSE2-NEXT:    ret <2 x i64> [[TMP3]]
;
; SLM-LABEL: @load_bytecast_ext(
; SLM-NEXT:    [[TMP1:%.*]] = load <2 x b8>, ptr [[P0:%.*]], align 1
; SLM-NEXT:    [[TMP2:%.*]] = bytecast <2 x b8> [[TMP1]] to <2 x i8>
; SLM-NEXT:    [[TMP3:%.*]] = zext <2 x i8> [[TMP2]] to <2 x i64>
; SLM-NEXT:    ret <2 x i64> [[TMP3]]
;
; AVX-LABEL: @load_bytecast_ext(
; AVX-NEXT:    [[TMP1:%.*]] = load <2 x b8>, ptr [[P0:%.*]], align 1
; AVX-NEXT:    [[TMP2:%.*]] = bytecast <2 x b8> [[TMP1]] to <2 x i8>
; AVX-NEXT:    [[TMP3:%.*]] = zext <2 x i8> [[TMP2]] to <2 x i64>
; AVX-NEXT:    ret <2 x i64> [[TMP3]]
;
  %p1 = getelementptr inbounds b8, ptr %p0, i64 1
  %b0 = load b8, ptr %p0, align 1
  %b1 = load b8, ptr %p1, align 1
  %i0 = bytecast b8 %b0 to i8
  %i1 = bytecast b8 %b1 to i8
  %x0 = zext i8 %i0 to i64
  %x1 = zext i8 %i1 to i64
  %v0 = insertelement <2 x i64> poison, i64 %x0, i32 0
  %v1 = insertelement <2 x i64>   %v0, i64 %x1, i32 1
  ret <2 x i64> %v1
}

define <8 x i8> @load_bytecast(ptr %p0) {
; SSE2-LABEL: @load_bytecast(
; SSE2-NEXT:    [[TMP1:%.*]] = load <8 x b8>, ptr [[P0:%.*]], align 1
; SSE2-NEXT:    [[TMP2:%.*]] = bytecast <8 x b8> [[TMP1]] to <8 x i8>
; SSE2-NEXT:    ret <8 x i8> [[TMP2]]
;
; SLM-LABEL: @load_bytecast(
; SLM-NEXT:    [[TMP1:%.*]] = load <8 x b8>, ptr [[P0:%.*]], align 1
; SLM-NEXT:    [[TMP2:%.*]] = bytecast <8 x b8> [[TMP1]] to <8 x i8>
; SLM-NEXT:    ret <8 x i8> [[TMP2]]
;
; AVX-LABEL: @load_bytecast(
; AVX-NEXT:    [[TMP1:%.*]] = load <8 x b8>, ptr [[P0:%.*]], align 1
; AVX-NEXT:    [[TMP2:%.*]] = bytecast <8 x b8> [[TMP1]] to <8 x i8>
; AVX-NEXT:    ret <8 x i8> [[TMP2]]
;
  %p1 = getelementptr inbounds b8, ptr %p0, i64 1
  %p2 = getelementptr inbounds b8, ptr %p0, i64 2
  %p3 = getelementptr inbounds b8, ptr %p0, i64 3
  %p4 = getelementptr inbounds b8, ptr %p0, i64 4
  %p5 = getelementptr inbounds b8, ptr %p0, i64 5
  %p6 = getelementptr inbounds b8, ptr %p0, i64 6
  %p7 = getelementptr inbounds b8, ptr %p0, i64 7
  %b0 = load b8, ptr %p0, align 1
  %b1 = load b8, ptr %p1, align 1
  %b2 = load b8, ptr %p2, align 1
  %b3 = load b8, ptr %p3, align 1
  %b4 = load b8, ptr %p4, align 1
  %b5 = load b8, ptr %p5, align 1
  %b6 = load b8, ptr %p6, align 1
  %b7 = load b8, ptr %p7, align 1
  %x0 = bytecast b8 %b0 to i8
  %x1 = bytecast b8 %b1 to i8
  %x2 = bytecast b8 %b2 to i8
  %x3 = bytecast b8 %b3 to i8
  %x4 = bytecast b8 %b4 to i8
  %x5 = bytecast b8 %b5 to i8
  %x6 = bytecast b8 %b6 to i8
  %x7 = bytecast b8 %b7 to i8
  %v0 = insertelement <8 x i8> poison, i8 %x0, i32 0
  %v1 = insertelement <8 x i8>   %v0, i8 %x1, i32 1
  %v2 = insertelement <8 x i8>   %v1, i8 %x2, i32 2
  %v3 = insertelement <8 x i8>   %v2, i8 %x3, i32 3
  %v4 = insertelement <8 x i8>   %v3, i8 %x4, i32 4
  %v5 = insertelement <8 x i8>   %v4, i8 %x5, i32 5
  %v6 = insertelement <8 x i8>   %v5, i8 %x6, i32 6
  %v7 = insertelement <8 x i8>   %v6, i8 %x7, i32 7
  ret <8 x i8> %v7
}
