// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %clang_cc1 -triple arm64-none-linux-gnu -target-feature +neon -target-feature +v8.5a\
// RUN: -flax-vector-conversions=none -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=mem2reg \
// RUN: | FileCheck %s

// REQUIRES: aarch64-registered-target

#include <arm_neon.h>

// CHECK-LABEL: define dso_local <2 x float> @test_vrnd32x_f32(
// CHECK-SAME: <2 x float> noundef [[A:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x float> [[A]] to <8 x b8>
// CHECK-NEXT:    [[VRND32X_F321_I:%.*]] = call <2 x float> @llvm.aarch64.neon.frint32x.v2f32(<2 x float> [[A]])
// CHECK-NEXT:    [[VRND32X_F322_I:%.*]] = bitcast <2 x float> [[VRND32X_F321_I]] to <8 x b8>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x b8> [[VRND32X_F322_I]] to <2 x b32>
// CHECK-NEXT:    [[TMP2:%.*]] = bytecast exact <2 x b32> [[TMP1]] to <2 x float>
// CHECK-NEXT:    ret <2 x float> [[TMP2]]
//
float32x2_t test_vrnd32x_f32(float32x2_t a) {
  return vrnd32x_f32(a);
}

// CHECK-LABEL: define dso_local <4 x float> @test_vrnd32xq_f32(
// CHECK-SAME: <4 x float> noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x float> [[A]] to <16 x b8>
// CHECK-NEXT:    [[VRND32XQ_F321_I:%.*]] = call <4 x float> @llvm.aarch64.neon.frint32x.v4f32(<4 x float> [[A]])
// CHECK-NEXT:    [[VRND32XQ_F322_I:%.*]] = bitcast <4 x float> [[VRND32XQ_F321_I]] to <16 x b8>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x b8> [[VRND32XQ_F322_I]] to <4 x b32>
// CHECK-NEXT:    [[TMP2:%.*]] = bytecast exact <4 x b32> [[TMP1]] to <4 x float>
// CHECK-NEXT:    ret <4 x float> [[TMP2]]
//
float32x4_t test_vrnd32xq_f32(float32x4_t a) {
  return vrnd32xq_f32(a);
}

// CHECK-LABEL: define dso_local <2 x float> @test_vrnd32z_f32(
// CHECK-SAME: <2 x float> noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x float> [[A]] to <8 x b8>
// CHECK-NEXT:    [[VRND32Z_F321_I:%.*]] = call <2 x float> @llvm.aarch64.neon.frint32z.v2f32(<2 x float> [[A]])
// CHECK-NEXT:    [[VRND32Z_F322_I:%.*]] = bitcast <2 x float> [[VRND32Z_F321_I]] to <8 x b8>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x b8> [[VRND32Z_F322_I]] to <2 x b32>
// CHECK-NEXT:    [[TMP2:%.*]] = bytecast exact <2 x b32> [[TMP1]] to <2 x float>
// CHECK-NEXT:    ret <2 x float> [[TMP2]]
//
float32x2_t test_vrnd32z_f32(float32x2_t a) {
  return vrnd32z_f32(a);
}

// CHECK-LABEL: define dso_local <4 x float> @test_vrnd32zq_f32(
// CHECK-SAME: <4 x float> noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x float> [[A]] to <16 x b8>
// CHECK-NEXT:    [[VRND32ZQ_F321_I:%.*]] = call <4 x float> @llvm.aarch64.neon.frint32z.v4f32(<4 x float> [[A]])
// CHECK-NEXT:    [[VRND32ZQ_F322_I:%.*]] = bitcast <4 x float> [[VRND32ZQ_F321_I]] to <16 x b8>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x b8> [[VRND32ZQ_F322_I]] to <4 x b32>
// CHECK-NEXT:    [[TMP2:%.*]] = bytecast exact <4 x b32> [[TMP1]] to <4 x float>
// CHECK-NEXT:    ret <4 x float> [[TMP2]]
//
float32x4_t test_vrnd32zq_f32(float32x4_t a) {
  return vrnd32zq_f32(a);
}

// CHECK-LABEL: define dso_local <2 x float> @test_vrnd64x_f32(
// CHECK-SAME: <2 x float> noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x float> [[A]] to <8 x b8>
// CHECK-NEXT:    [[VRND64X_F321_I:%.*]] = call <2 x float> @llvm.aarch64.neon.frint64x.v2f32(<2 x float> [[A]])
// CHECK-NEXT:    [[VRND64X_F322_I:%.*]] = bitcast <2 x float> [[VRND64X_F321_I]] to <8 x b8>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x b8> [[VRND64X_F322_I]] to <2 x b32>
// CHECK-NEXT:    [[TMP2:%.*]] = bytecast exact <2 x b32> [[TMP1]] to <2 x float>
// CHECK-NEXT:    ret <2 x float> [[TMP2]]
//
float32x2_t test_vrnd64x_f32(float32x2_t a) {
  return vrnd64x_f32(a);
}

// CHECK-LABEL: define dso_local <4 x float> @test_vrnd64xq_f32(
// CHECK-SAME: <4 x float> noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x float> [[A]] to <16 x b8>
// CHECK-NEXT:    [[VRND64XQ_F321_I:%.*]] = call <4 x float> @llvm.aarch64.neon.frint64x.v4f32(<4 x float> [[A]])
// CHECK-NEXT:    [[VRND64XQ_F322_I:%.*]] = bitcast <4 x float> [[VRND64XQ_F321_I]] to <16 x b8>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x b8> [[VRND64XQ_F322_I]] to <4 x b32>
// CHECK-NEXT:    [[TMP2:%.*]] = bytecast exact <4 x b32> [[TMP1]] to <4 x float>
// CHECK-NEXT:    ret <4 x float> [[TMP2]]
//
float32x4_t test_vrnd64xq_f32(float32x4_t a) {
  return vrnd64xq_f32(a);
}

// CHECK-LABEL: define dso_local <2 x float> @test_vrnd64z_f32(
// CHECK-SAME: <2 x float> noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x float> [[A]] to <8 x b8>
// CHECK-NEXT:    [[VRND64Z_F321_I:%.*]] = call <2 x float> @llvm.aarch64.neon.frint64z.v2f32(<2 x float> [[A]])
// CHECK-NEXT:    [[VRND64Z_F322_I:%.*]] = bitcast <2 x float> [[VRND64Z_F321_I]] to <8 x b8>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x b8> [[VRND64Z_F322_I]] to <2 x b32>
// CHECK-NEXT:    [[TMP2:%.*]] = bytecast exact <2 x b32> [[TMP1]] to <2 x float>
// CHECK-NEXT:    ret <2 x float> [[TMP2]]
//
float32x2_t test_vrnd64z_f32(float32x2_t a) {
  return vrnd64z_f32(a);
}

// CHECK-LABEL: define dso_local <4 x float> @test_vrnd64zq_f32(
// CHECK-SAME: <4 x float> noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x float> [[A]] to <16 x b8>
// CHECK-NEXT:    [[VRND64ZQ_F321_I:%.*]] = call <4 x float> @llvm.aarch64.neon.frint64z.v4f32(<4 x float> [[A]])
// CHECK-NEXT:    [[VRND64ZQ_F322_I:%.*]] = bitcast <4 x float> [[VRND64ZQ_F321_I]] to <16 x b8>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x b8> [[VRND64ZQ_F322_I]] to <4 x b32>
// CHECK-NEXT:    [[TMP2:%.*]] = bytecast exact <4 x b32> [[TMP1]] to <4 x float>
// CHECK-NEXT:    ret <4 x float> [[TMP2]]
//
float32x4_t test_vrnd64zq_f32(float32x4_t a) {
  return vrnd64zq_f32(a);
}

// CHECK-LABEL: define dso_local <1 x double> @test_vrnd32x_f64(
// CHECK-SAME: <1 x double> noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <1 x double> [[A]] to <8 x b8>
// CHECK-NEXT:    [[VRND32X_F641_I:%.*]] = call <1 x double> @llvm.aarch64.neon.frint32x.v1f64(<1 x double> [[A]])
// CHECK-NEXT:    [[VRND32X_F642_I:%.*]] = bitcast <1 x double> [[VRND32X_F641_I]] to <8 x b8>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x b8> [[VRND32X_F642_I]] to <1 x b64>
// CHECK-NEXT:    [[TMP2:%.*]] = bytecast exact <1 x b64> [[TMP1]] to <1 x double>
// CHECK-NEXT:    ret <1 x double> [[TMP2]]
//
float64x1_t test_vrnd32x_f64(float64x1_t a) {
  return vrnd32x_f64(a);
}

// CHECK-LABEL: define dso_local <2 x double> @test_vrnd32xq_f64(
// CHECK-SAME: <2 x double> noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x double> [[A]] to <16 x b8>
// CHECK-NEXT:    [[VRND32XQ_F641_I:%.*]] = call <2 x double> @llvm.aarch64.neon.frint32x.v2f64(<2 x double> [[A]])
// CHECK-NEXT:    [[VRND32XQ_F642_I:%.*]] = bitcast <2 x double> [[VRND32XQ_F641_I]] to <16 x b8>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x b8> [[VRND32XQ_F642_I]] to <2 x b64>
// CHECK-NEXT:    [[TMP2:%.*]] = bytecast exact <2 x b64> [[TMP1]] to <2 x double>
// CHECK-NEXT:    ret <2 x double> [[TMP2]]
//
float64x2_t test_vrnd32xq_f64(float64x2_t a) {
  return vrnd32xq_f64(a);
}

// CHECK-LABEL: define dso_local <1 x double> @test_vrnd32z_f64(
// CHECK-SAME: <1 x double> noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <1 x double> [[A]] to <8 x b8>
// CHECK-NEXT:    [[VRND32Z_F641_I:%.*]] = call <1 x double> @llvm.aarch64.neon.frint32z.v1f64(<1 x double> [[A]])
// CHECK-NEXT:    [[VRND32Z_F642_I:%.*]] = bitcast <1 x double> [[VRND32Z_F641_I]] to <8 x b8>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x b8> [[VRND32Z_F642_I]] to <1 x b64>
// CHECK-NEXT:    [[TMP2:%.*]] = bytecast exact <1 x b64> [[TMP1]] to <1 x double>
// CHECK-NEXT:    ret <1 x double> [[TMP2]]
//
float64x1_t test_vrnd32z_f64(float64x1_t a) {
  return vrnd32z_f64(a);
}

// CHECK-LABEL: define dso_local <2 x double> @test_vrnd32zq_f64(
// CHECK-SAME: <2 x double> noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x double> [[A]] to <16 x b8>
// CHECK-NEXT:    [[VRND32ZQ_F641_I:%.*]] = call <2 x double> @llvm.aarch64.neon.frint32z.v2f64(<2 x double> [[A]])
// CHECK-NEXT:    [[VRND32ZQ_F642_I:%.*]] = bitcast <2 x double> [[VRND32ZQ_F641_I]] to <16 x b8>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x b8> [[VRND32ZQ_F642_I]] to <2 x b64>
// CHECK-NEXT:    [[TMP2:%.*]] = bytecast exact <2 x b64> [[TMP1]] to <2 x double>
// CHECK-NEXT:    ret <2 x double> [[TMP2]]
//
float64x2_t test_vrnd32zq_f64(float64x2_t a) {
  return vrnd32zq_f64(a);
}

// CHECK-LABEL: define dso_local <1 x double> @test_vrnd64x_f64(
// CHECK-SAME: <1 x double> noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <1 x double> [[A]] to <8 x b8>
// CHECK-NEXT:    [[VRND64X_F641_I:%.*]] = call <1 x double> @llvm.aarch64.neon.frint64x.v1f64(<1 x double> [[A]])
// CHECK-NEXT:    [[VRND64X_F642_I:%.*]] = bitcast <1 x double> [[VRND64X_F641_I]] to <8 x b8>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x b8> [[VRND64X_F642_I]] to <1 x b64>
// CHECK-NEXT:    [[TMP2:%.*]] = bytecast exact <1 x b64> [[TMP1]] to <1 x double>
// CHECK-NEXT:    ret <1 x double> [[TMP2]]
//
float64x1_t test_vrnd64x_f64(float64x1_t a) {
  return vrnd64x_f64(a);
}

// CHECK-LABEL: define dso_local <2 x double> @test_vrnd64xq_f64(
// CHECK-SAME: <2 x double> noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x double> [[A]] to <16 x b8>
// CHECK-NEXT:    [[VRND64XQ_F641_I:%.*]] = call <2 x double> @llvm.aarch64.neon.frint64x.v2f64(<2 x double> [[A]])
// CHECK-NEXT:    [[VRND64XQ_F642_I:%.*]] = bitcast <2 x double> [[VRND64XQ_F641_I]] to <16 x b8>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x b8> [[VRND64XQ_F642_I]] to <2 x b64>
// CHECK-NEXT:    [[TMP2:%.*]] = bytecast exact <2 x b64> [[TMP1]] to <2 x double>
// CHECK-NEXT:    ret <2 x double> [[TMP2]]
//
float64x2_t test_vrnd64xq_f64(float64x2_t a) {
  return vrnd64xq_f64(a);
}

// CHECK-LABEL: define dso_local <1 x double> @test_vrnd64z_f64(
// CHECK-SAME: <1 x double> noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <1 x double> [[A]] to <8 x b8>
// CHECK-NEXT:    [[VRND64Z_F641_I:%.*]] = call <1 x double> @llvm.aarch64.neon.frint64z.v1f64(<1 x double> [[A]])
// CHECK-NEXT:    [[VRND64Z_F642_I:%.*]] = bitcast <1 x double> [[VRND64Z_F641_I]] to <8 x b8>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x b8> [[VRND64Z_F642_I]] to <1 x b64>
// CHECK-NEXT:    [[TMP2:%.*]] = bytecast exact <1 x b64> [[TMP1]] to <1 x double>
// CHECK-NEXT:    ret <1 x double> [[TMP2]]
//
float64x1_t test_vrnd64z_f64(float64x1_t a) {
  return vrnd64z_f64(a);
}

// CHECK-LABEL: define dso_local <2 x double> @test_vrnd64zq_f64(
// CHECK-SAME: <2 x double> noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x double> [[A]] to <16 x b8>
// CHECK-NEXT:    [[VRND64ZQ_F641_I:%.*]] = call <2 x double> @llvm.aarch64.neon.frint64z.v2f64(<2 x double> [[A]])
// CHECK-NEXT:    [[VRND64ZQ_F642_I:%.*]] = bitcast <2 x double> [[VRND64ZQ_F641_I]] to <16 x b8>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x b8> [[VRND64ZQ_F642_I]] to <2 x b64>
// CHECK-NEXT:    [[TMP2:%.*]] = bytecast exact <2 x b64> [[TMP1]] to <2 x double>
// CHECK-NEXT:    ret <2 x double> [[TMP2]]
//
float64x2_t test_vrnd64zq_f64(float64x2_t a) {
  return vrnd64zq_f64(a);
}
