; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=aggressive-instcombine -S | FileCheck %s

define b16 @test(i64 %i, i1 %cmp) {
; CHECK-LABEL: @test(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[CMP:%.*]], label [[EXIT:%.*]], label [[THEN:%.*]]
; CHECK:       then:
; CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i64 [[I:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP_I]], label [[EXIT]], label [[BB:%.*]]
; CHECK:       bb:
; CHECK-NEXT:    [[BB_OP:%.*]] = phi b16 [ 0, [[THEN]] ]
; CHECK-NEXT:    ret b16 [[BB_OP]]
; CHECK:       exit:
; CHECK-NEXT:    [[TRUNC:%.*]] = phi b16 [ 0, [[THEN]] ], [ 11, [[ENTRY:%.*]] ]
; CHECK-NEXT:    ret b16 [[TRUNC]]
;
entry:
  br i1 %cmp, label %exit, label %then

then:
  %cmp.i = icmp eq i64 %i, 0
  br i1 %cmp.i, label %exit, label %bb

bb:
  %bb.op = phi b16 [ 0, %then ]
  ret b16 %bb.op

exit:
  %ret = phi b32 [ 0, %then ], [ 65547, %entry ]
  %trunc = trunc b32 %ret to b16
  ret b16 %trunc
}

