; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=jump-threading -S < %s | FileCheck %s

define i1 @test1(i1 %cond) {
; CHECK-LABEL: @test1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[EXIT_FALSE:%.*]], label [[EXIT_TRUE:%.*]]
; CHECK:       exit.true:
; CHECK-NEXT:    ret i1 true
; CHECK:       exit.false:
; CHECK-NEXT:    [[RET1:%.*]] = phi b32 [ 16, [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[I:%.*]] = bytecast b32 [[RET1]] to i32
; CHECK-NEXT:    ret i1 false
;
entry:
  br i1 %cond, label %then, label %merge

then:
  %ret1 = phi b32 [ 16, %entry ]
  br label %merge

merge:
  %ret2 = phi b32 [ %ret1, %then ], [ 0, %entry ]
  %i = bytecast b32 %ret2 to i32
  %cmp = icmp eq i32 %i, 0
  br i1 %cmp, label %exit.true, label %exit.false

exit.true:
  ret i1 true

exit.false:
  ret i1 false
}

