; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define void @extract-bytecast(<16 x b8> %vec, ptr %p) {
; CHECK-LABEL: define void @extract-bytecast(
; CHECK-SAME: <16 x b8> [[VEC:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C:%.*]] = bytecast <16 x b8> [[VEC]] to <2 x i64>
; CHECK-NEXT:    [[E:%.*]] = extractelement <2 x i64> [[C]], i64 0
; CHECK-NEXT:    store i64 [[E]], ptr [[P]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %c = bytecast <16 x b8> %vec to <2 x i64>
  %e = extractelement <2 x i64> %c, i64 0
  store i64 %e, ptr %p
  ret void
}
