; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=instcombine < %s | FileCheck %s

; If a pointer is loaded as an integer, the load returns poison and the bitcast
; to byte has a distinct value from a byte load. Therefore, the load + bitcast
; to byte cannot be combined.
define b64 @test(i1 %c, ptr %p) {
; CHECK-LABEL: @test(
; CHECK-NEXT:    [[LOAD:%.*]] = load i64, ptr [[P:%.*]], align 8
; CHECK-NEXT:    [[CAST:%.*]] = bitcast i64 [[LOAD]] to b64
; CHECK-NEXT:    ret b64 [[CAST]]
;
  %load = load i64, ptr %p, align 8
  %cast = bitcast i64 %load to b64
  ret b64 %cast
}
