; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; This select instruction can't be eliminated because trying to do so would
; change the number of vector elements.
define <8 x i16> @test1(<16 x b8> %v, <16 x i1> %cmp) {
; CHECK-LABEL: @test1(
; CHECK-NEXT:    [[TMP1:%.*]] = select <16 x i1> [[CMP:%.*]], <16 x b8> [[V:%.*]], <16 x b8> zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = bytecast <16 x b8> [[TMP1]] to <8 x i16>
; CHECK-NEXT:    ret <8 x i16> [[TMP2]]
;
  %2 = select <16 x i1> %cmp, <16 x b8> %v, <16 x b8> zeroinitializer
  %3 = bytecast <16 x b8> %2 to <8 x i16>
  ret <8 x i16> %3
}

; Can't change the type of the vector select if the dest type is scalar.
define b32 @test2(b32 %x, <2 x b16> %y, <4 x i1> %cmp) {
; CHECK-LABEL: @test2(
; CHECK-NEXT:    [[T4:%.*]] = bytecast b32 [[X:%.*]] to <4 x i8>
; CHECK-NEXT:    [[T5:%.*]] = bytecast <2 x b16> [[Y:%.*]] to <4 x i8>
; CHECK-NEXT:    [[T6:%.*]] = select <4 x i1> [[CMP:%.*]], <4 x i8> [[T4]], <4 x i8> [[T5]]
; CHECK-NEXT:    [[T7:%.*]] = bitcast <4 x i8> [[T6]] to b32
; CHECK-NEXT:    ret b32 [[T7]]
;
  %t4 = bytecast b32 %x to <4 x i8>
  %t5 = bytecast <2 x b16> %y to <4 x i8>
  %t6 = select <4 x i1> %cmp, <4 x i8> %t4, <4 x i8> %t5
  %t7 = bitcast <4 x i8> %t6 to b32
  ret b32 %t7
}

; We can optimize an element-wise bytecast.
define <4 x float> @test3(i1 %cmp, <4 x b32> %v) {
; CHECK-LABEL: @test3(
; CHECK-NEXT:    [[TMP1:%.*]] = bytecast <4 x b32> [[V:%.*]] to <4 x float>
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[CMP:%.*]], <4 x float> splat (float 0x36A0000000000000), <4 x float> [[TMP1]]
; CHECK-NEXT:    ret <4 x float> [[TMP2]]
;
  %1 = select i1 %cmp, <4 x b32> <b32 1, b32 1, b32 1, b32 1>, <4 x b32> %v
  %2 = bytecast <4 x b32> %1 to <4 x float>
  ret <4 x float> %2
}

