; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt %s -S -passes=byte-replacer -o - | FileCheck %s

@global = global b8 0
@extern_global = external global b8
@array_global = external global [8 x b8]

define <8 x b8> @args_ret(b8 %a, b32 %b, <8 x b8> %c) {
; CHECK-LABEL: define <8 x i8> @args_ret(
; CHECK-SAME: i8 [[A:%.*]], i32 [[B:%.*]], <8 x i8> [[C:%.*]]) {
; CHECK-NEXT:    ret <8 x i8> [[C]]
;
  ret <8 x b8> %c
}

define i8 @bytecasts(b8 %a, <16 x b8> %b) {
; CHECK-LABEL: define i8 @bytecasts(
; CHECK-SAME: i8 [[A:%.*]], <16 x i8> [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[B]] to <4 x i32>
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> undef to <4 x i32>
; CHECK-NEXT:    ret i8 0
;
  %tmp1 = bytecast b8 %a to i8
  %tmp2 = bytecast <16 x b8> %b to <16 x i8>
  %tmp3 = bytecast <16 x b8> %b to <4 x i32>
  %tmp4 = bytecast b8 0 to i8
  %tmp5 = bytecast <16 x b8> undef to <16 x i8>
  %tmp6 = bytecast <16 x b8> undef to <4 x i32>
  ret i8 %tmp4
}

define b8 @bitcasts(i8 %a, <16 x i8> %b) {
; CHECK-LABEL: define i8 @bitcasts(
; CHECK-SAME: i8 [[A:%.*]], <16 x i8> [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[B]] to <4 x i32>
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> undef to <4 x i32>
; CHECK-NEXT:    ret i8 0
;
  %tmp1 = bitcast i8 %a to b8
  %tmp2 = bitcast <16 x i8> %b to <16 x b8>
  %tmp3 = bitcast <16 x i8> %b to <4 x b32>
  %tmp4 = bitcast i8 0 to b8
  %tmp5 = bitcast <16 x i8> undef to <16 x b8>
  %tmp6 = bitcast <16 x i8> undef to <4 x b32>
  ret b8 %tmp4
}

declare i32 @llvm.loongarch.lsx.bz.v(<16 x i8>)
define i32 @casts(i128 %_1.coerce) {
; CHECK-LABEL: define i32 @casts(
; CHECK-SAME: i128 [[_1_COERCE:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast i128 [[_1_COERCE]] to <16 x i8>
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @llvm.loongarch.lsx.bz.v(<16 x i8> [[TMP1]])
; CHECK-NEXT:    ret i32 [[TMP2]]
;
  %1 = bitcast i128 %_1.coerce to <16 x b8>
  %2 = bytecast <16 x b8> %1 to <16 x i8>
  %3 = call i32 @llvm.loongarch.lsx.bz.v(<16 x i8> %2)
  ret i32 %3
}


define <4 x i16> @call_bytecast() {
; CHECK-LABEL: define <4 x i16> @call_bytecast() {
; CHECK-NEXT:    [[TMP1:%.*]] = call <8 x i8> @args_ret(i8 1, i32 2, <8 x i8> undef)
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i8> [[TMP1]] to <4 x i16>
; CHECK-NEXT:    ret <4 x i16> [[TMP1]]
;
  %tmp1 = call <8 x b8> @args_ret(b8 1, b32 2, <8 x b8> undef)
  %tmp2 = bytecast <8 x b8> %tmp1 to <4 x i16>
  ret <4 x i16> %tmp2
}

define void @allocas() {
; CHECK-LABEL: define void @allocas() {
; CHECK-NEXT:    [[A:%.*]] = alloca i8, align 1
; CHECK-NEXT:    [[B:%.*]] = alloca <8 x i8>, align 8
; CHECK-NEXT:    ret void
;
  %a = alloca b8
  %b = alloca <8 x b8>
  ret void
}

define void @loads_stores(ptr %a, ptr %b) {
; CHECK-LABEL: define void @loads_stores(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:    [[C:%.*]] = load i8, ptr [[A]], align 1
; CHECK-NEXT:    [[D:%.*]] = load <8 x i8>, ptr [[B]], align 8
; CHECK-NEXT:    store i8 [[C]], ptr [[A]], align 1
; CHECK-NEXT:    store <8 x i8> [[D]], ptr [[B]], align 8
; CHECK-NEXT:    store i8 0, ptr [[A]], align 1
; CHECK-NEXT:    store <8 x i8> undef, ptr [[B]], align 8
; CHECK-NEXT:    ret void
;
  %c = load b8, ptr %a
  %d = load <8 x b8>, ptr %b
  store b8 %c, ptr %a
  store <8 x b8> %d, ptr %b
  store b8 0, ptr %a
  store <8 x b8> undef, ptr %b
  ret void
}

define i8 @calls() {
; CHECK-LABEL: define i8 @calls() {
; CHECK-NEXT:    [[A:%.*]] = call <8 x i8> @args_ret(i8 1, i32 2, <8 x i8> undef)
; CHECK-NEXT:    [[B:%.*]] = call i8 @bytecasts(i8 3, <16 x i8> undef)
; CHECK-NEXT:    [[C:%.*]] = call i8 @bitcasts(i8 4, <16 x i8> undef)
; CHECK-NEXT:    ret i8 [[C]]
;
  %a = call <8 x b8> @args_ret(b8 1, b32 2, <8 x b8> undef)
  %b = call i8 @bytecasts(b8 3, <16 x b8> undef)
  %c = call b8 @bitcasts(i8 4, <16 x i8> undef)
  %d = bytecast b8 %c to i8
  ret i8 %d
}

define void @shuffle(<8 x b8> %a, <8 x b8> %b) {
; CHECK-LABEL: define void @shuffle(
; CHECK-SAME: <8 x i8> [[A:%.*]], <8 x i8> [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i8> [[A]], <8 x i8> [[B]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    ret void
;
  %tmp1 = shufflevector <8 x b8> %a, <8 x b8> %b, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret void
}

define void @select(<8 x b8> %a, <8 x b8> %b, <8 x i1> %c) {
; CHECK-LABEL: define void @select(
; CHECK-SAME: <8 x i8> [[A:%.*]], <8 x i8> [[B:%.*]], <8 x i1> [[C:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = select <8 x i1> [[C]], <8 x i8> [[A]], <8 x i8> [[B]]
; CHECK-NEXT:    ret void
;
  %tmp1 = select <8 x i1> %c, <8 x b8> %a, <8 x b8> %b
  ret void
}

define void @gep(ptr %p) {
; CHECK-LABEL: define void @gep(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds [8 x i8], ptr [[P]], i32 0, i32 0
; CHECK-NEXT:    ret void
;
  %tmp1 = getelementptr inbounds [8 x b8], ptr %p, i32 0, i32 0
  ret void
}

define void @structs({ b8, <8 x b8> } %a) {
; CHECK-LABEL: define void @structs(
; CHECK-SAME: { i8, <8 x i8> } [[A:%.*]]) {
; CHECK-NEXT:    ret void
;
  ret void
}

define void @phis(b8 %a, b8 %b) {
; CHECK-LABEL: define void @phis(
; CHECK-SAME: i8 [[A:%.*]], i8 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[BLOCK:.*]]
; CHECK:       [[BLOCK]]:
; CHECK-NEXT:    [[TMP1:%.*]] = phi i8 [ [[A]], %[[ENTRY]] ], [ [[B]], %[[BLOCK]] ]
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i8 [[TMP1]], 0
; CHECK-NEXT:    br i1 [[COND]], label %[[EXIT:.*]], label %[[BLOCK]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %block

block:
  %tmp1 = phi b8 [ %a, %entry ], [ %b, %block ]
  %tmp2 = bytecast b8 %tmp1 to i8
  %cond = icmp eq i8 %tmp2, 0
  br i1 %cond, label %exit, label %block

exit:
  ret void
}
