; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=instsimplify -S | FileCheck %s

define b8 @test1() {
; CHECK-LABEL: define b8 @test1() {
; CHECK-NEXT:    ret b8 1
;
  %1 = bitcast i8 1 to b8
  ret b8 %1
}

define b32 @test2() {
; CHECK-LABEL: define b32 @test2() {
; CHECK-NEXT:    ret b32 1077936128
;
  %1 = bitcast float 3.0 to b32
  ret b32 %1
}

define <4 x b8> @test3() {
; CHECK-LABEL: define <4 x b8> @test3() {
; CHECK-NEXT:    ret <4 x b8> <b8 1, b8 2, b8 3, b8 4>
;
  %1 = bitcast <4 x i8> <i8 1, i8 2, i8 3, i8 4> to <4 x b8>
  ret <4 x b8> %1
}

define <4 x b32> @test4() {
; CHECK-LABEL: define <4 x b32> @test4() {
; CHECK-NEXT:    ret <4 x b32> <b32 1077936128, b32 1082130432, b32 1084227584, b32 1086324736>
;
  %1 = bitcast <4 x float> <float 3.0, float 4.0, float 5.0, float 6.0> to <4 x b32>
  ret <4 x b32> %1
}

define i8 @test5() {
; CHECK-LABEL: define i8 @test5() {
; CHECK-NEXT:    ret i8 1
;
  %1 = bytecast b8 1 to i8
  ret i8 %1
}

define float @test6() {
; CHECK-LABEL: define float @test6() {
; CHECK-NEXT:    ret float 0x36D4000000000000
;
  %1 = bytecast b32 10 to float
  ret float %1
}

define <4 x i8> @test7() {
; CHECK-LABEL: define <4 x i8> @test7() {
; CHECK-NEXT:    ret <4 x i8> <i8 1, i8 2, i8 3, i8 4>
;
  %1 = bytecast <4 x b8> <b8 1, b8 2, b8 3, b8 4> to <4 x i8>
  ret <4 x i8> %1
}

define <4 x float> @test8() {
; CHECK-LABEL: define <4 x float> @test8() {
; CHECK-NEXT:    ret <4 x float> <float 0x36D4000000000000, float 0x36D6000000000000, float 0x36D8000000000000, float 0x36DA000000000000>
;
  %1 = bytecast <4 x b32> <b32 10, b32 11, b32 12, b32 13> to <4 x float>
  ret <4 x float> %1
}

define b32 @test9() {
; CHECK-LABEL: define b32 @test9() {
; CHECK-NEXT:    ret b32 1
;
  ret b32 trunc (b64 1 to b32)
}

define i32 @test10() {
; CHECK-LABEL: define i32 @test10() {
; CHECK-NEXT:    ret i32 1
;
  ret i32 bytecast (b32 trunc (b64 1 to b32) to i32)
}

