// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %clang_cc1 -triple x86_64-apple-darwin -O1 -no-struct-path-tbaa -disable-llvm-passes %s -emit-llvm -o - | FileCheck %s
// RUN: %clang_cc1 -triple x86_64-apple-darwin -O1 -disable-llvm-passes %s -emit-llvm -o - | FileCheck %s -check-prefixes=PATH,OLD-PATH
// RUN: %clang_cc1 -triple x86_64-apple-darwin -O1 -new-struct-path-tbaa -disable-llvm-passes %s -emit-llvm -o - | FileCheck %s -check-prefixes=PATH,NEW-PATH
// RUN: %clang_cc1 -triple x86_64-apple-darwin -O0 -disable-llvm-passes %s -emit-llvm -o - | FileCheck %s -check-prefix=NO-TBAA
// RUN: %clang_cc1 -triple x86_64-apple-darwin -O1 -relaxed-aliasing -disable-llvm-passes %s -emit-llvm -o - | FileCheck %s -check-prefix=NO-TBAA
// Test TBAA metadata generated by front-end.
//

typedef unsigned char uint8_t;
typedef unsigned short uint16_t;
typedef unsigned int uint32_t;
typedef unsigned long long uint64_t;
typedef struct
{
   uint16_t f16;
   uint32_t f32;
   uint16_t f16_2;
   uint32_t f32_2;
} StructA;
typedef struct
{
   uint16_t f16;
   StructA a;
   uint32_t f32;
} StructB;
typedef struct
{
   uint16_t f16;
   StructB b;
   uint32_t f32;
} StructC;
typedef struct
{
   uint16_t f16;
   StructB b;
   uint32_t f32;
   uint8_t f8;
} StructD;

typedef struct
{
   uint16_t f16;
   uint32_t f32;
} StructS;
typedef struct
{
   uint16_t f16;
   uint32_t f32;
} StructS2;

// CHECK-LABEL: define noundef i32 @_Z1gPjP7StructAy(
// CHECK-SAME: ptr noundef [[S:%.*]], ptr noundef [[A:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8, !tbaa [[TBAA6:![0-9]+]]
// CHECK-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA9:![0-9]+]]
// CHECK-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10:![0-9]+]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA6]]
// CHECK-NEXT:    store i32 1, ptr [[TMP0]], align 4, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP1]], i32 0, i32 1
// CHECK-NEXT:    store i32 4, ptr [[F32]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA6]]
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP2]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret i32 [[TMP3]]
//
// PATH-LABEL: define noundef i32 @_Z1gPjP7StructAy(
// PATH-SAME: ptr noundef [[S:%.*]], ptr noundef [[A:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0:[0-9]+]] {
// PATH-NEXT:  [[ENTRY:.*:]]
// PATH-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// PATH-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8, !tbaa [[TBAA6:![0-9]+]]
// PATH-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA9:![0-9]+]]
// PATH-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10:![0-9]+]]
// PATH-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA6]]
// PATH-NEXT:    store i32 1, ptr [[TMP0]], align 4, !tbaa [[TBAA2:![0-9]+]]
// PATH-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP1]], i32 0, i32 1
// PATH-NEXT:    store i32 4, ptr [[F32]], align 4, !tbaa [[TBAA12:![0-9]+]]
// PATH-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA6]]
// PATH-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP2]], align 4, !tbaa [[TBAA2]]
// PATH-NEXT:    ret i32 [[TMP3]]
//
// NO-TBAA-LABEL: define noundef i32 @_Z1gPjP7StructAy(
// NO-TBAA-SAME: ptr noundef [[S:%.*]], ptr noundef [[A:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0:[0-9]+]] {
// NO-TBAA-NEXT:  [[ENTRY:.*:]]
// NO-TBAA-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// NO-TBAA-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8
// NO-TBAA-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[S_ADDR]], align 8
// NO-TBAA-NEXT:    store i32 1, ptr [[TMP0]], align 4
// NO-TBAA-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP1]], i32 0, i32 1
// NO-TBAA-NEXT:    store i32 4, ptr [[F32]], align 4
// NO-TBAA-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[S_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP2]], align 4
// NO-TBAA-NEXT:    ret i32 [[TMP3]]
//
uint32_t g(uint32_t *s, StructA *A, uint64_t count) {
  *s = 1;
  A->f32 = 4;
  return *s;
}

// CHECK-LABEL: define noundef i32 @_Z2g2PjP7StructAy(
// CHECK-SAME: ptr noundef [[S:%.*]], ptr noundef [[A:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8, !tbaa [[TBAA6]]
// CHECK-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA6]]
// CHECK-NEXT:    store i32 1, ptr [[TMP0]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F16:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP1]], i32 0, i32 0
// CHECK-NEXT:    store i16 4, ptr [[F16]], align 4, !tbaa [[TBAA12:![0-9]+]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA6]]
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP2]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret i32 [[TMP3]]
//
// PATH-LABEL: define noundef i32 @_Z2g2PjP7StructAy(
// PATH-SAME: ptr noundef [[S:%.*]], ptr noundef [[A:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// PATH-NEXT:  [[ENTRY:.*:]]
// PATH-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// PATH-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8, !tbaa [[TBAA6]]
// PATH-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// PATH-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA6]]
// PATH-NEXT:    store i32 1, ptr [[TMP0]], align 4, !tbaa [[TBAA2]]
// PATH-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F16:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP1]], i32 0, i32 0
// PATH-NEXT:    store i16 4, ptr [[F16]], align 4, !tbaa [[TBAA15:![0-9]+]]
// PATH-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA6]]
// PATH-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP2]], align 4, !tbaa [[TBAA2]]
// PATH-NEXT:    ret i32 [[TMP3]]
//
// NO-TBAA-LABEL: define noundef i32 @_Z2g2PjP7StructAy(
// NO-TBAA-SAME: ptr noundef [[S:%.*]], ptr noundef [[A:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// NO-TBAA-NEXT:  [[ENTRY:.*:]]
// NO-TBAA-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// NO-TBAA-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8
// NO-TBAA-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[S_ADDR]], align 8
// NO-TBAA-NEXT:    store i32 1, ptr [[TMP0]], align 4
// NO-TBAA-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    [[F16:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP1]], i32 0, i32 0
// NO-TBAA-NEXT:    store i16 4, ptr [[F16]], align 4
// NO-TBAA-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[S_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP2]], align 4
// NO-TBAA-NEXT:    ret i32 [[TMP3]]
//
uint32_t g2(uint32_t *s, StructA *A, uint64_t count) {
  *s = 1;
  A->f16 = 4;
  return *s;
}

// CHECK-LABEL: define noundef i32 @_Z2g3P7StructAP7StructBy(
// CHECK-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[A:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB:%.*]], ptr [[TMP1]], i32 0, i32 1
// CHECK-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[A]], i32 0, i32 1
// CHECK-NEXT:    store i32 4, ptr [[F321]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F322:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[TMP2]], i32 0, i32 1
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F322]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret i32 [[TMP3]]
//
// PATH-LABEL: define noundef i32 @_Z2g3P7StructAP7StructBy(
// PATH-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// PATH-NEXT:  [[ENTRY:.*:]]
// PATH-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// PATH-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// PATH-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP0]], i32 0, i32 1
// PATH-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA12]]
// PATH-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[A:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB:%.*]], ptr [[TMP1]], i32 0, i32 1
// PATH-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[A]], i32 0, i32 1
// PATH-NEXT:    store i32 4, ptr [[F321]], align 4, !tbaa [[TBAA16:![0-9]+]]
// PATH-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F322:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[TMP2]], i32 0, i32 1
// PATH-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F322]], align 4, !tbaa [[TBAA12]]
// PATH-NEXT:    ret i32 [[TMP3]]
//
// NO-TBAA-LABEL: define noundef i32 @_Z2g3P7StructAP7StructBy(
// NO-TBAA-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// NO-TBAA-NEXT:  [[ENTRY:.*:]]
// NO-TBAA-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// NO-TBAA-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// NO-TBAA-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP0]], i32 0, i32 1
// NO-TBAA-NEXT:    store i32 1, ptr [[F32]], align 4
// NO-TBAA-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B_ADDR]], align 8
// NO-TBAA-NEXT:    [[A:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB:%.*]], ptr [[TMP1]], i32 0, i32 1
// NO-TBAA-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[A]], i32 0, i32 1
// NO-TBAA-NEXT:    store i32 4, ptr [[F321]], align 4
// NO-TBAA-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    [[F322:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[TMP2]], i32 0, i32 1
// NO-TBAA-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F322]], align 4
// NO-TBAA-NEXT:    ret i32 [[TMP3]]
//
uint32_t g3(StructA *A, StructB *B, uint64_t count) {
  A->f32 = 1;
  B->a.f32 = 4;
  return A->f32;
}

// CHECK-LABEL: define noundef i32 @_Z2g4P7StructAP7StructBy(
// CHECK-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[A:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB:%.*]], ptr [[TMP1]], i32 0, i32 1
// CHECK-NEXT:    [[F16:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[A]], i32 0, i32 0
// CHECK-NEXT:    store i16 4, ptr [[F16]], align 4, !tbaa [[TBAA12]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[TMP2]], i32 0, i32 1
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F321]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret i32 [[TMP3]]
//
// PATH-LABEL: define noundef i32 @_Z2g4P7StructAP7StructBy(
// PATH-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// PATH-NEXT:  [[ENTRY:.*:]]
// PATH-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// PATH-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// PATH-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP0]], i32 0, i32 1
// PATH-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA12]]
// PATH-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[A:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB:%.*]], ptr [[TMP1]], i32 0, i32 1
// PATH-NEXT:    [[F16:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[A]], i32 0, i32 0
// PATH-NEXT:    store i16 4, ptr [[F16]], align 4, !tbaa [[TBAA18:![0-9]+]]
// PATH-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[TMP2]], i32 0, i32 1
// PATH-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F321]], align 4, !tbaa [[TBAA12]]
// PATH-NEXT:    ret i32 [[TMP3]]
//
// NO-TBAA-LABEL: define noundef i32 @_Z2g4P7StructAP7StructBy(
// NO-TBAA-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// NO-TBAA-NEXT:  [[ENTRY:.*:]]
// NO-TBAA-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// NO-TBAA-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// NO-TBAA-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP0]], i32 0, i32 1
// NO-TBAA-NEXT:    store i32 1, ptr [[F32]], align 4
// NO-TBAA-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B_ADDR]], align 8
// NO-TBAA-NEXT:    [[A:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB:%.*]], ptr [[TMP1]], i32 0, i32 1
// NO-TBAA-NEXT:    [[F16:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[A]], i32 0, i32 0
// NO-TBAA-NEXT:    store i16 4, ptr [[F16]], align 4
// NO-TBAA-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[TMP2]], i32 0, i32 1
// NO-TBAA-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F321]], align 4
// NO-TBAA-NEXT:    ret i32 [[TMP3]]
//
uint32_t g4(StructA *A, StructB *B, uint64_t count) {
  A->f32 = 1;
  B->a.f16 = 4;
  return A->f32;
}

// CHECK-LABEL: define noundef i32 @_Z2g5P7StructAP7StructBy(
// CHECK-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB:%.*]], ptr [[TMP1]], i32 0, i32 2
// CHECK-NEXT:    store i32 4, ptr [[F321]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F322:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[TMP2]], i32 0, i32 1
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F322]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret i32 [[TMP3]]
//
// PATH-LABEL: define noundef i32 @_Z2g5P7StructAP7StructBy(
// PATH-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// PATH-NEXT:  [[ENTRY:.*:]]
// PATH-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// PATH-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// PATH-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP0]], i32 0, i32 1
// PATH-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA12]]
// PATH-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB:%.*]], ptr [[TMP1]], i32 0, i32 2
// PATH-NEXT:    store i32 4, ptr [[F321]], align 4, !tbaa [[TBAA19:![0-9]+]]
// PATH-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F322:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[TMP2]], i32 0, i32 1
// PATH-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F322]], align 4, !tbaa [[TBAA12]]
// PATH-NEXT:    ret i32 [[TMP3]]
//
// NO-TBAA-LABEL: define noundef i32 @_Z2g5P7StructAP7StructBy(
// NO-TBAA-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// NO-TBAA-NEXT:  [[ENTRY:.*:]]
// NO-TBAA-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// NO-TBAA-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// NO-TBAA-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP0]], i32 0, i32 1
// NO-TBAA-NEXT:    store i32 1, ptr [[F32]], align 4
// NO-TBAA-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B_ADDR]], align 8
// NO-TBAA-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB:%.*]], ptr [[TMP1]], i32 0, i32 2
// NO-TBAA-NEXT:    store i32 4, ptr [[F321]], align 4
// NO-TBAA-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    [[F322:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[TMP2]], i32 0, i32 1
// NO-TBAA-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F322]], align 4
// NO-TBAA-NEXT:    ret i32 [[TMP3]]
//
uint32_t g5(StructA *A, StructB *B, uint64_t count) {
  A->f32 = 1;
  B->f32 = 4;
  return A->f32;
}

// CHECK-LABEL: define noundef i32 @_Z2g6P7StructAP7StructBy(
// CHECK-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[A:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB:%.*]], ptr [[TMP1]], i32 0, i32 1
// CHECK-NEXT:    [[F32_2:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[A]], i32 0, i32 3
// CHECK-NEXT:    store i32 4, ptr [[F32_2]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[TMP2]], i32 0, i32 1
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F321]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret i32 [[TMP3]]
//
// PATH-LABEL: define noundef i32 @_Z2g6P7StructAP7StructBy(
// PATH-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// PATH-NEXT:  [[ENTRY:.*:]]
// PATH-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// PATH-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// PATH-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP0]], i32 0, i32 1
// PATH-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA12]]
// PATH-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[A:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB:%.*]], ptr [[TMP1]], i32 0, i32 1
// PATH-NEXT:    [[F32_2:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[A]], i32 0, i32 3
// PATH-NEXT:    store i32 4, ptr [[F32_2]], align 4, !tbaa [[TBAA20:![0-9]+]]
// PATH-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[TMP2]], i32 0, i32 1
// PATH-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F321]], align 4, !tbaa [[TBAA12]]
// PATH-NEXT:    ret i32 [[TMP3]]
//
// NO-TBAA-LABEL: define noundef i32 @_Z2g6P7StructAP7StructBy(
// NO-TBAA-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// NO-TBAA-NEXT:  [[ENTRY:.*:]]
// NO-TBAA-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// NO-TBAA-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// NO-TBAA-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP0]], i32 0, i32 1
// NO-TBAA-NEXT:    store i32 1, ptr [[F32]], align 4
// NO-TBAA-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B_ADDR]], align 8
// NO-TBAA-NEXT:    [[A:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB:%.*]], ptr [[TMP1]], i32 0, i32 1
// NO-TBAA-NEXT:    [[F32_2:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[A]], i32 0, i32 3
// NO-TBAA-NEXT:    store i32 4, ptr [[F32_2]], align 4
// NO-TBAA-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[TMP2]], i32 0, i32 1
// NO-TBAA-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F321]], align 4
// NO-TBAA-NEXT:    ret i32 [[TMP3]]
//
uint32_t g6(StructA *A, StructB *B, uint64_t count) {
  A->f32 = 1;
  B->a.f32_2 = 4;
  return A->f32;
}

// CHECK-LABEL: define noundef i32 @_Z2g7P7StructAP7StructSy(
// CHECK-SAME: ptr noundef [[A:%.*]], ptr noundef [[S:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS:%.*]], ptr [[TMP1]], i32 0, i32 1
// CHECK-NEXT:    store i32 4, ptr [[F321]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F322:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[TMP2]], i32 0, i32 1
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F322]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret i32 [[TMP3]]
//
// PATH-LABEL: define noundef i32 @_Z2g7P7StructAP7StructSy(
// PATH-SAME: ptr noundef [[A:%.*]], ptr noundef [[S:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// PATH-NEXT:  [[ENTRY:.*:]]
// PATH-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// PATH-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// PATH-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP0]], i32 0, i32 1
// PATH-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA12]]
// PATH-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS:%.*]], ptr [[TMP1]], i32 0, i32 1
// PATH-NEXT:    store i32 4, ptr [[F321]], align 4, !tbaa [[TBAA21:![0-9]+]]
// PATH-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F322:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[TMP2]], i32 0, i32 1
// PATH-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F322]], align 4, !tbaa [[TBAA12]]
// PATH-NEXT:    ret i32 [[TMP3]]
//
// NO-TBAA-LABEL: define noundef i32 @_Z2g7P7StructAP7StructSy(
// NO-TBAA-SAME: ptr noundef [[A:%.*]], ptr noundef [[S:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// NO-TBAA-NEXT:  [[ENTRY:.*:]]
// NO-TBAA-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// NO-TBAA-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8
// NO-TBAA-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP0]], i32 0, i32 1
// NO-TBAA-NEXT:    store i32 1, ptr [[F32]], align 4
// NO-TBAA-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[S_ADDR]], align 8
// NO-TBAA-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS:%.*]], ptr [[TMP1]], i32 0, i32 1
// NO-TBAA-NEXT:    store i32 4, ptr [[F321]], align 4
// NO-TBAA-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    [[F322:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[TMP2]], i32 0, i32 1
// NO-TBAA-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F322]], align 4
// NO-TBAA-NEXT:    ret i32 [[TMP3]]
//
uint32_t g7(StructA *A, StructS *S, uint64_t count) {
  A->f32 = 1;
  S->f32 = 4;
  return A->f32;
}

// CHECK-LABEL: define noundef i32 @_Z2g8P7StructAP7StructSy(
// CHECK-SAME: ptr noundef [[A:%.*]], ptr noundef [[S:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F16:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS:%.*]], ptr [[TMP1]], i32 0, i32 0
// CHECK-NEXT:    store i16 4, ptr [[F16]], align 4, !tbaa [[TBAA12]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[TMP2]], i32 0, i32 1
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F321]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret i32 [[TMP3]]
//
// PATH-LABEL: define noundef i32 @_Z2g8P7StructAP7StructSy(
// PATH-SAME: ptr noundef [[A:%.*]], ptr noundef [[S:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// PATH-NEXT:  [[ENTRY:.*:]]
// PATH-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// PATH-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// PATH-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP0]], i32 0, i32 1
// PATH-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA12]]
// PATH-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F16:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS:%.*]], ptr [[TMP1]], i32 0, i32 0
// PATH-NEXT:    store i16 4, ptr [[F16]], align 4, !tbaa [[TBAA23:![0-9]+]]
// PATH-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[TMP2]], i32 0, i32 1
// PATH-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F321]], align 4, !tbaa [[TBAA12]]
// PATH-NEXT:    ret i32 [[TMP3]]
//
// NO-TBAA-LABEL: define noundef i32 @_Z2g8P7StructAP7StructSy(
// NO-TBAA-SAME: ptr noundef [[A:%.*]], ptr noundef [[S:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// NO-TBAA-NEXT:  [[ENTRY:.*:]]
// NO-TBAA-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// NO-TBAA-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8
// NO-TBAA-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[TMP0]], i32 0, i32 1
// NO-TBAA-NEXT:    store i32 1, ptr [[F32]], align 4
// NO-TBAA-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[S_ADDR]], align 8
// NO-TBAA-NEXT:    [[F16:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS:%.*]], ptr [[TMP1]], i32 0, i32 0
// NO-TBAA-NEXT:    store i16 4, ptr [[F16]], align 4
// NO-TBAA-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[TMP2]], i32 0, i32 1
// NO-TBAA-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F321]], align 4
// NO-TBAA-NEXT:    ret i32 [[TMP3]]
//
uint32_t g8(StructA *A, StructS *S, uint64_t count) {
  A->f32 = 1;
  S->f16 = 4;
  return A->f32;
}

// CHECK-LABEL: define noundef i32 @_Z2g9P7StructSP8StructS2y(
// CHECK-SAME: ptr noundef [[S:%.*]], ptr noundef [[S2:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[S2_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store ptr [[S2]], ptr [[S2_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS:%.*]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[S2_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS2:%.*]], ptr [[TMP1]], i32 0, i32 1
// CHECK-NEXT:    store i32 4, ptr [[F321]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F322:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS]], ptr [[TMP2]], i32 0, i32 1
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F322]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret i32 [[TMP3]]
//
// PATH-LABEL: define noundef i32 @_Z2g9P7StructSP8StructS2y(
// PATH-SAME: ptr noundef [[S:%.*]], ptr noundef [[S2:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// PATH-NEXT:  [[ENTRY:.*:]]
// PATH-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[S2_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// PATH-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store ptr [[S2]], ptr [[S2_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// PATH-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS:%.*]], ptr [[TMP0]], i32 0, i32 1
// PATH-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA21]]
// PATH-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[S2_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS2:%.*]], ptr [[TMP1]], i32 0, i32 1
// PATH-NEXT:    store i32 4, ptr [[F321]], align 4, !tbaa [[TBAA24:![0-9]+]]
// PATH-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F322:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS]], ptr [[TMP2]], i32 0, i32 1
// PATH-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F322]], align 4, !tbaa [[TBAA21]]
// PATH-NEXT:    ret i32 [[TMP3]]
//
// NO-TBAA-LABEL: define noundef i32 @_Z2g9P7StructSP8StructS2y(
// NO-TBAA-SAME: ptr noundef [[S:%.*]], ptr noundef [[S2:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// NO-TBAA-NEXT:  [[ENTRY:.*:]]
// NO-TBAA-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[S2_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// NO-TBAA-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8
// NO-TBAA-NEXT:    store ptr [[S2]], ptr [[S2_ADDR]], align 8
// NO-TBAA-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[S_ADDR]], align 8
// NO-TBAA-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS:%.*]], ptr [[TMP0]], i32 0, i32 1
// NO-TBAA-NEXT:    store i32 1, ptr [[F32]], align 4
// NO-TBAA-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[S2_ADDR]], align 8
// NO-TBAA-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS2:%.*]], ptr [[TMP1]], i32 0, i32 1
// NO-TBAA-NEXT:    store i32 4, ptr [[F321]], align 4
// NO-TBAA-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[S_ADDR]], align 8
// NO-TBAA-NEXT:    [[F322:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS]], ptr [[TMP2]], i32 0, i32 1
// NO-TBAA-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F322]], align 4
// NO-TBAA-NEXT:    ret i32 [[TMP3]]
//
uint32_t g9(StructS *S, StructS2 *S2, uint64_t count) {
  S->f32 = 1;
  S2->f32 = 4;
  return S->f32;
}

// CHECK-LABEL: define noundef i32 @_Z3g10P7StructSP8StructS2y(
// CHECK-SAME: ptr noundef [[S:%.*]], ptr noundef [[S2:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[S2_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store ptr [[S2]], ptr [[S2_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS:%.*]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[S2_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F16:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS2:%.*]], ptr [[TMP1]], i32 0, i32 0
// CHECK-NEXT:    store i16 4, ptr [[F16]], align 4, !tbaa [[TBAA12]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS]], ptr [[TMP2]], i32 0, i32 1
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F321]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret i32 [[TMP3]]
//
// PATH-LABEL: define noundef i32 @_Z3g10P7StructSP8StructS2y(
// PATH-SAME: ptr noundef [[S:%.*]], ptr noundef [[S2:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// PATH-NEXT:  [[ENTRY:.*:]]
// PATH-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[S2_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// PATH-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store ptr [[S2]], ptr [[S2_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// PATH-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS:%.*]], ptr [[TMP0]], i32 0, i32 1
// PATH-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA21]]
// PATH-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[S2_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F16:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS2:%.*]], ptr [[TMP1]], i32 0, i32 0
// PATH-NEXT:    store i16 4, ptr [[F16]], align 4, !tbaa [[TBAA26:![0-9]+]]
// PATH-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS]], ptr [[TMP2]], i32 0, i32 1
// PATH-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F321]], align 4, !tbaa [[TBAA21]]
// PATH-NEXT:    ret i32 [[TMP3]]
//
// NO-TBAA-LABEL: define noundef i32 @_Z3g10P7StructSP8StructS2y(
// NO-TBAA-SAME: ptr noundef [[S:%.*]], ptr noundef [[S2:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// NO-TBAA-NEXT:  [[ENTRY:.*:]]
// NO-TBAA-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[S2_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// NO-TBAA-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8
// NO-TBAA-NEXT:    store ptr [[S2]], ptr [[S2_ADDR]], align 8
// NO-TBAA-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[S_ADDR]], align 8
// NO-TBAA-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS:%.*]], ptr [[TMP0]], i32 0, i32 1
// NO-TBAA-NEXT:    store i32 1, ptr [[F32]], align 4
// NO-TBAA-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[S2_ADDR]], align 8
// NO-TBAA-NEXT:    [[F16:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS2:%.*]], ptr [[TMP1]], i32 0, i32 0
// NO-TBAA-NEXT:    store i16 4, ptr [[F16]], align 4
// NO-TBAA-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[S_ADDR]], align 8
// NO-TBAA-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS]], ptr [[TMP2]], i32 0, i32 1
// NO-TBAA-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F321]], align 4
// NO-TBAA-NEXT:    ret i32 [[TMP3]]
//
uint32_t g10(StructS *S, StructS2 *S2, uint64_t count) {
  S->f32 = 1;
  S2->f16 = 4;
  return S->f32;
}

// CHECK-LABEL: define noundef i32 @_Z3g11P7StructCP7StructDy(
// CHECK-SAME: ptr noundef [[C:%.*]], ptr noundef [[D:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[C_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[D_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store ptr [[C]], ptr [[C_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store ptr [[D]], ptr [[D_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[C_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[B:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTC:%.*]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[A:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB:%.*]], ptr [[B]], i32 0, i32 1
// CHECK-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[A]], i32 0, i32 1
// CHECK-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[D_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[B1:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTD:%.*]], ptr [[TMP1]], i32 0, i32 1
// CHECK-NEXT:    [[A2:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB]], ptr [[B1]], i32 0, i32 1
// CHECK-NEXT:    [[F323:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[A2]], i32 0, i32 1
// CHECK-NEXT:    store i32 4, ptr [[F323]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[C_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[B4:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTC]], ptr [[TMP2]], i32 0, i32 1
// CHECK-NEXT:    [[A5:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB]], ptr [[B4]], i32 0, i32 1
// CHECK-NEXT:    [[F326:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[A5]], i32 0, i32 1
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F326]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret i32 [[TMP3]]
//
// PATH-LABEL: define noundef i32 @_Z3g11P7StructCP7StructDy(
// PATH-SAME: ptr noundef [[C:%.*]], ptr noundef [[D:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// PATH-NEXT:  [[ENTRY:.*:]]
// PATH-NEXT:    [[C_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[D_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// PATH-NEXT:    store ptr [[C]], ptr [[C_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store ptr [[D]], ptr [[D_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// PATH-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[C_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[B:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTC:%.*]], ptr [[TMP0]], i32 0, i32 1
// PATH-NEXT:    [[A:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB:%.*]], ptr [[B]], i32 0, i32 1
// PATH-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[A]], i32 0, i32 1
// PATH-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA27:![0-9]+]]
// PATH-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[D_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[B1:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTD:%.*]], ptr [[TMP1]], i32 0, i32 1
// PATH-NEXT:    [[A2:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB]], ptr [[B1]], i32 0, i32 1
// PATH-NEXT:    [[F323:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[A2]], i32 0, i32 1
// PATH-NEXT:    store i32 4, ptr [[F323]], align 4, !tbaa [[TBAA29:![0-9]+]]
// PATH-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[C_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[B4:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTC]], ptr [[TMP2]], i32 0, i32 1
// PATH-NEXT:    [[A5:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB]], ptr [[B4]], i32 0, i32 1
// PATH-NEXT:    [[F326:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[A5]], i32 0, i32 1
// PATH-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F326]], align 4, !tbaa [[TBAA27]]
// PATH-NEXT:    ret i32 [[TMP3]]
//
// NO-TBAA-LABEL: define noundef i32 @_Z3g11P7StructCP7StructDy(
// NO-TBAA-SAME: ptr noundef [[C:%.*]], ptr noundef [[D:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// NO-TBAA-NEXT:  [[ENTRY:.*:]]
// NO-TBAA-NEXT:    [[C_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[D_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// NO-TBAA-NEXT:    store ptr [[C]], ptr [[C_ADDR]], align 8
// NO-TBAA-NEXT:    store ptr [[D]], ptr [[D_ADDR]], align 8
// NO-TBAA-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[C_ADDR]], align 8
// NO-TBAA-NEXT:    [[B:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTC:%.*]], ptr [[TMP0]], i32 0, i32 1
// NO-TBAA-NEXT:    [[A:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB:%.*]], ptr [[B]], i32 0, i32 1
// NO-TBAA-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[A]], i32 0, i32 1
// NO-TBAA-NEXT:    store i32 1, ptr [[F32]], align 4
// NO-TBAA-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[D_ADDR]], align 8
// NO-TBAA-NEXT:    [[B1:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTD:%.*]], ptr [[TMP1]], i32 0, i32 1
// NO-TBAA-NEXT:    [[A2:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB]], ptr [[B1]], i32 0, i32 1
// NO-TBAA-NEXT:    [[F323:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[A2]], i32 0, i32 1
// NO-TBAA-NEXT:    store i32 4, ptr [[F323]], align 4
// NO-TBAA-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[C_ADDR]], align 8
// NO-TBAA-NEXT:    [[B4:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTC]], ptr [[TMP2]], i32 0, i32 1
// NO-TBAA-NEXT:    [[A5:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB]], ptr [[B4]], i32 0, i32 1
// NO-TBAA-NEXT:    [[F326:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[A5]], i32 0, i32 1
// NO-TBAA-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F326]], align 4
// NO-TBAA-NEXT:    ret i32 [[TMP3]]
//
uint32_t g11(StructC *C, StructD *D, uint64_t count) {
  C->b.a.f32 = 1;
  D->b.a.f32 = 4;
  return C->b.a.f32;
}

// CHECK-LABEL: define noundef i32 @_Z3g12P7StructCP7StructDy(
// CHECK-SAME: ptr noundef [[C:%.*]], ptr noundef [[D:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[C_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[D_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[B1:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[B2:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[C]], ptr [[C_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store ptr [[D]], ptr [[D_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[B1]]) #[[ATTR2:[0-9]+]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[C_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[B:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTC:%.*]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[B]], ptr [[B1]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[B2]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[D_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[B3:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTD:%.*]], ptr [[TMP1]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[B3]], ptr [[B2]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[B1]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[A:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB:%.*]], ptr [[TMP2]], i32 0, i32 1
// CHECK-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[A]], i32 0, i32 1
// CHECK-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[B2]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[A4:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB]], ptr [[TMP3]], i32 0, i32 1
// CHECK-NEXT:    [[F325:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[A4]], i32 0, i32 1
// CHECK-NEXT:    store i32 4, ptr [[F325]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[B1]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[A6:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB]], ptr [[TMP4]], i32 0, i32 1
// CHECK-NEXT:    [[F327:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[A6]], i32 0, i32 1
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[F327]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[B2]]) #[[ATTR2]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[B1]]) #[[ATTR2]]
// CHECK-NEXT:    ret i32 [[TMP5]]
//
// PATH-LABEL: define noundef i32 @_Z3g12P7StructCP7StructDy(
// PATH-SAME: ptr noundef [[C:%.*]], ptr noundef [[D:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// PATH-NEXT:  [[ENTRY:.*:]]
// PATH-NEXT:    [[C_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[D_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// PATH-NEXT:    [[B1:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[B2:%.*]] = alloca ptr, align 8
// PATH-NEXT:    store ptr [[C]], ptr [[C_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store ptr [[D]], ptr [[D_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// PATH-NEXT:    call void @llvm.lifetime.start.p0(ptr [[B1]]) #[[ATTR2:[0-9]+]]
// PATH-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[C_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[B:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTC:%.*]], ptr [[TMP0]], i32 0, i32 1
// PATH-NEXT:    store ptr [[B]], ptr [[B1]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    call void @llvm.lifetime.start.p0(ptr [[B2]]) #[[ATTR2]]
// PATH-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[D_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[B3:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTD:%.*]], ptr [[TMP1]], i32 0, i32 1
// PATH-NEXT:    store ptr [[B3]], ptr [[B2]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[B1]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[A:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB:%.*]], ptr [[TMP2]], i32 0, i32 1
// PATH-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA:%.*]], ptr [[A]], i32 0, i32 1
// PATH-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA16]]
// PATH-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[B2]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[A4:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB]], ptr [[TMP3]], i32 0, i32 1
// PATH-NEXT:    [[F325:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[A4]], i32 0, i32 1
// PATH-NEXT:    store i32 4, ptr [[F325]], align 4, !tbaa [[TBAA16]]
// PATH-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[B1]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[A6:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTB]], ptr [[TMP4]], i32 0, i32 1
// PATH-NEXT:    [[F327:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTA]], ptr [[A6]], i32 0, i32 1
// PATH-NEXT:    [[TMP5:%.*]] = load i32, ptr [[F327]], align 4, !tbaa [[TBAA16]]
// PATH-NEXT:    call void @llvm.lifetime.end.p0(ptr [[B2]]) #[[ATTR2]]
// PATH-NEXT:    call void @llvm.lifetime.end.p0(ptr [[B1]]) #[[ATTR2]]
// PATH-NEXT:    ret i32 [[TMP5]]
//
uint32_t g12(StructC *C, StructD *D, uint64_t count) {
// TODO: differentiate the two accesses.
  StructB *b1 = &(C->b);
  StructB *b2 = &(D->b);
  // b1, b2 have different context.
  b1->a.f32 = 1;
  b2->a.f32 = 4;
  return b1->a.f32;
}

// Make sure that zero-length bitfield works.
#define ATTR __attribute__ ((ms_struct))
struct five {
  char a;
  int :0;        /* ignored; prior field is not a bitfield. */
  char b;
  char c;
} ATTR;
// CHECK-LABEL: define noundef signext b8 @_Z3g13P4fiveS0_(
// CHECK-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA14:![0-9]+]]
// CHECK-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8, !tbaa [[TBAA14]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA14]]
// CHECK-NEXT:    [[B1:%.*]] = getelementptr inbounds nuw [[STRUCT_FIVE:%.*]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[TMP1:%.*]] = load b8, ptr [[B1]], align 1, !tbaa [[TBAA16:![0-9]+]]
// CHECK-NEXT:    ret b8 [[TMP1]]
//
// PATH-LABEL: define noundef signext b8 @_Z3g13P4fiveS0_(
// PATH-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]]) #[[ATTR0]] {
// PATH-NEXT:  [[ENTRY:.*:]]
// PATH-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA31:![0-9]+]]
// PATH-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8, !tbaa [[TBAA31]]
// PATH-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA31]]
// PATH-NEXT:    [[B1:%.*]] = getelementptr inbounds nuw [[STRUCT_FIVE:%.*]], ptr [[TMP0]], i32 0, i32 1
// PATH-NEXT:    [[TMP1:%.*]] = load b8, ptr [[B1]], align 1, !tbaa [[TBAA33:![0-9]+]]
// PATH-NEXT:    ret b8 [[TMP1]]
//
// NO-TBAA-LABEL: define noundef signext b8 @_Z3g13P4fiveS0_(
// NO-TBAA-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]]) #[[ATTR0]] {
// NO-TBAA-NEXT:  [[ENTRY:.*:]]
// NO-TBAA-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    [[B1:%.*]] = getelementptr inbounds nuw [[STRUCT_FIVE:%.*]], ptr [[TMP0]], i32 0, i32 1
// NO-TBAA-NEXT:    [[TMP1:%.*]] = load b8, ptr [[B1]], align 1
// NO-TBAA-NEXT:    ret b8 [[TMP1]]
//
char g13(struct five *a, struct five *b) {
  return a->b;
}

struct six {
  char a;
  int :0;
  char b;
  char c;
};
// CHECK-LABEL: define noundef signext b8 @_Z3g14P3sixS0_(
// CHECK-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA17:![0-9]+]]
// CHECK-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8, !tbaa [[TBAA17]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA17]]
// CHECK-NEXT:    [[B1:%.*]] = getelementptr inbounds nuw [[STRUCT_SIX:%.*]], ptr [[TMP0]], i32 0, i32 2
// CHECK-NEXT:    [[TMP1:%.*]] = load b8, ptr [[B1]], align 1, !tbaa [[TBAA16]]
// CHECK-NEXT:    ret b8 [[TMP1]]
//
// PATH-LABEL: define noundef signext b8 @_Z3g14P3sixS0_(
// PATH-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]]) #[[ATTR0]] {
// PATH-NEXT:  [[ENTRY:.*:]]
// PATH-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8, !tbaa [[TBAA35:![0-9]+]]
// PATH-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8, !tbaa [[TBAA35]]
// PATH-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !tbaa [[TBAA35]]
// PATH-NEXT:    [[B1:%.*]] = getelementptr inbounds nuw [[STRUCT_SIX:%.*]], ptr [[TMP0]], i32 0, i32 2
// PATH-NEXT:    [[TMP1:%.*]] = load b8, ptr [[B1]], align 1, !tbaa [[TBAA37:![0-9]+]]
// PATH-NEXT:    ret b8 [[TMP1]]
//
// NO-TBAA-LABEL: define noundef signext b8 @_Z3g14P3sixS0_(
// NO-TBAA-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]]) #[[ATTR0]] {
// NO-TBAA-NEXT:  [[ENTRY:.*:]]
// NO-TBAA-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// NO-TBAA-NEXT:    [[B1:%.*]] = getelementptr inbounds nuw [[STRUCT_SIX:%.*]], ptr [[TMP0]], i32 0, i32 2
// NO-TBAA-NEXT:    [[TMP1:%.*]] = load b8, ptr [[B1]], align 1
// NO-TBAA-NEXT:    ret b8 [[TMP1]]
//
char g14(struct six *a, struct six *b) {
  return a->b;
}

// Types that differ only by name may alias.
typedef StructS StructS3;
// CHECK-LABEL: define noundef i32 @_Z3g15P7StructSS0_y(
// CHECK-SAME: ptr noundef [[S:%.*]], ptr noundef [[S3:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[S3_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store ptr [[S3]], ptr [[S3_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS:%.*]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[S3_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS]], ptr [[TMP1]], i32 0, i32 1
// CHECK-NEXT:    store i32 4, ptr [[F321]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[F322:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS]], ptr [[TMP2]], i32 0, i32 1
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F322]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret i32 [[TMP3]]
//
// PATH-LABEL: define noundef i32 @_Z3g15P7StructSS0_y(
// PATH-SAME: ptr noundef [[S:%.*]], ptr noundef [[S3:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// PATH-NEXT:  [[ENTRY:.*:]]
// PATH-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[S3_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// PATH-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store ptr [[S3]], ptr [[S3_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8, !tbaa [[TBAA10]]
// PATH-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS:%.*]], ptr [[TMP0]], i32 0, i32 1
// PATH-NEXT:    store i32 1, ptr [[F32]], align 4, !tbaa [[TBAA21]]
// PATH-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[S3_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS]], ptr [[TMP1]], i32 0, i32 1
// PATH-NEXT:    store i32 4, ptr [[F321]], align 4, !tbaa [[TBAA21]]
// PATH-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !tbaa [[TBAA9]]
// PATH-NEXT:    [[F322:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS]], ptr [[TMP2]], i32 0, i32 1
// PATH-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F322]], align 4, !tbaa [[TBAA21]]
// PATH-NEXT:    ret i32 [[TMP3]]
//
// NO-TBAA-LABEL: define noundef i32 @_Z3g15P7StructSS0_y(
// NO-TBAA-SAME: ptr noundef [[S:%.*]], ptr noundef [[S3:%.*]], i64 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// NO-TBAA-NEXT:  [[ENTRY:.*:]]
// NO-TBAA-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[S3_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[COUNT_ADDR:%.*]] = alloca i64, align 8
// NO-TBAA-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8
// NO-TBAA-NEXT:    store ptr [[S3]], ptr [[S3_ADDR]], align 8
// NO-TBAA-NEXT:    store i64 [[COUNT]], ptr [[COUNT_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[S_ADDR]], align 8
// NO-TBAA-NEXT:    [[F32:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS:%.*]], ptr [[TMP0]], i32 0, i32 1
// NO-TBAA-NEXT:    store i32 1, ptr [[F32]], align 4
// NO-TBAA-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[S3_ADDR]], align 8
// NO-TBAA-NEXT:    [[F321:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS]], ptr [[TMP1]], i32 0, i32 1
// NO-TBAA-NEXT:    store i32 4, ptr [[F321]], align 4
// NO-TBAA-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[S_ADDR]], align 8
// NO-TBAA-NEXT:    [[F322:%.*]] = getelementptr inbounds nuw [[STRUCT_STRUCTS]], ptr [[TMP2]], i32 0, i32 1
// NO-TBAA-NEXT:    [[TMP3:%.*]] = load i32, ptr [[F322]], align 4
// NO-TBAA-NEXT:    ret i32 [[TMP3]]
//
uint32_t g15(StructS *S, StructS3 *S3, uint64_t count) {
  S->f32 = 1;
  S3->f32 = 4;
  return S->f32;
}

//.
// CHECK: [[TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// CHECK: [[META3]] = !{!"int", [[META4:![0-9]+]], i64 0}
// CHECK: [[META4]] = !{!"omnipotent char", [[META5:![0-9]+]], i64 0}
// CHECK: [[META5]] = !{!"Simple C++ TBAA"}
// CHECK: [[TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
// CHECK: [[META7]] = !{!"p1 int", [[META8:![0-9]+]], i64 0}
// CHECK: [[META8]] = !{!"any pointer", [[META4]], i64 0}
// CHECK: [[TBAA9]] = !{[[META8]], [[META8]], i64 0}
// CHECK: [[TBAA10]] = !{[[META11:![0-9]+]], [[META11]], i64 0}
// CHECK: [[META11]] = !{!"long long", [[META4]], i64 0}
// CHECK: [[TBAA12]] = !{[[META13:![0-9]+]], [[META13]], i64 0}
// CHECK: [[META13]] = !{!"short", [[META4]], i64 0}
// CHECK: [[TBAA14]] = !{[[META15:![0-9]+]], [[META15]], i64 0}
// CHECK: [[META15]] = !{!"p1 _ZTS4five", [[META8]], i64 0}
// CHECK: [[TBAA16]] = !{[[META4]], [[META4]], i64 0}
// CHECK: [[TBAA17]] = !{[[META18:![0-9]+]], [[META18]], i64 0}
// CHECK: [[META18]] = !{!"p1 _ZTS3six", [[META8]], i64 0}
//.
// OLD-PATH: [[TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// OLD-PATH: [[META3]] = !{!"int", [[META4:![0-9]+]], i64 0}
// OLD-PATH: [[META4]] = !{!"omnipotent char", [[META5:![0-9]+]], i64 0}
// OLD-PATH: [[META5]] = !{!"Simple C++ TBAA"}
// OLD-PATH: [[TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
// OLD-PATH: [[META7]] = !{!"p1 int", [[META8:![0-9]+]], i64 0}
// OLD-PATH: [[META8]] = !{!"any pointer", [[META4]], i64 0}
// OLD-PATH: [[TBAA9]] = !{[[META8]], [[META8]], i64 0}
// OLD-PATH: [[TBAA10]] = !{[[META11:![0-9]+]], [[META11]], i64 0}
// OLD-PATH: [[META11]] = !{!"long long", [[META4]], i64 0}
// OLD-PATH: [[TBAA12]] = !{[[META13:![0-9]+]], [[META3]], i64 4}
// OLD-PATH: [[META13]] = !{!"_ZTS7StructA", [[META14:![0-9]+]], i64 0, [[META3]], i64 4, [[META14]], i64 8, [[META3]], i64 12}
// OLD-PATH: [[META14]] = !{!"short", [[META4]], i64 0}
// OLD-PATH: [[TBAA15]] = !{[[META13]], [[META14]], i64 0}
// OLD-PATH: [[TBAA16]] = !{[[META17:![0-9]+]], [[META3]], i64 8}
// OLD-PATH: [[META17]] = !{!"_ZTS7StructB", [[META14]], i64 0, [[META13]], i64 4, [[META3]], i64 20}
// OLD-PATH: [[TBAA18]] = !{[[META17]], [[META14]], i64 4}
// OLD-PATH: [[TBAA19]] = !{[[META17]], [[META3]], i64 20}
// OLD-PATH: [[TBAA20]] = !{[[META17]], [[META3]], i64 16}
// OLD-PATH: [[TBAA21]] = !{[[META22:![0-9]+]], [[META3]], i64 4}
// OLD-PATH: [[META22]] = !{!"_ZTS7StructS", [[META14]], i64 0, [[META3]], i64 4}
// OLD-PATH: [[TBAA23]] = !{[[META22]], [[META14]], i64 0}
// OLD-PATH: [[TBAA24]] = !{[[META25:![0-9]+]], [[META3]], i64 4}
// OLD-PATH: [[META25]] = !{!"_ZTS8StructS2", [[META14]], i64 0, [[META3]], i64 4}
// OLD-PATH: [[TBAA26]] = !{[[META25]], [[META14]], i64 0}
// OLD-PATH: [[TBAA27]] = !{[[META28:![0-9]+]], [[META3]], i64 12}
// OLD-PATH: [[META28]] = !{!"_ZTS7StructC", [[META14]], i64 0, [[META17]], i64 4, [[META3]], i64 28}
// OLD-PATH: [[TBAA29]] = !{[[META30:![0-9]+]], [[META3]], i64 12}
// OLD-PATH: [[META30]] = !{!"_ZTS7StructD", [[META14]], i64 0, [[META17]], i64 4, [[META3]], i64 28, [[META4]], i64 32}
// OLD-PATH: [[TBAA31]] = !{[[META32:![0-9]+]], [[META32]], i64 0}
// OLD-PATH: [[META32]] = !{!"p1 _ZTS4five", [[META8]], i64 0}
// OLD-PATH: [[TBAA33]] = !{[[META34:![0-9]+]], [[META4]], i64 1}
// OLD-PATH: [[META34]] = !{!"_ZTS4five", [[META4]], i64 0, [[META4]], i64 1, [[META4]], i64 2}
// OLD-PATH: [[TBAA35]] = !{[[META36:![0-9]+]], [[META36]], i64 0}
// OLD-PATH: [[META36]] = !{!"p1 _ZTS3six", [[META8]], i64 0}
// OLD-PATH: [[TBAA37]] = !{[[META38:![0-9]+]], [[META4]], i64 4}
// OLD-PATH: [[META38]] = !{!"_ZTS3six", [[META4]], i64 0, [[META4]], i64 4, [[META4]], i64 5}
//.
// NEW-PATH: [[TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0, i64 4}
// NEW-PATH: [[META3]] = !{[[META4:![0-9]+]], i64 4, !"int"}
// NEW-PATH: [[META4]] = !{[[META5:![0-9]+]], i64 1, !"omnipotent char"}
// NEW-PATH: [[META5]] = !{!"Simple C++ TBAA"}
// NEW-PATH: [[TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0, i64 8}
// NEW-PATH: [[META7]] = !{[[META8:![0-9]+]], i64 8, !"p1 int"}
// NEW-PATH: [[META8]] = !{[[META4]], i64 8, !"any pointer"}
// NEW-PATH: [[TBAA9]] = !{[[META8]], [[META8]], i64 0, i64 8}
// NEW-PATH: [[TBAA10]] = !{[[META11:![0-9]+]], [[META11]], i64 0, i64 8}
// NEW-PATH: [[META11]] = !{[[META4]], i64 8, !"long long"}
// NEW-PATH: [[TBAA12]] = !{[[META13:![0-9]+]], [[META3]], i64 4, i64 4}
// NEW-PATH: [[META13]] = !{[[META4]], i64 16, !"_ZTS7StructA", [[META14:![0-9]+]], i64 0, i64 2, [[META3]], i64 4, i64 4, [[META14]], i64 8, i64 2, [[META3]], i64 12, i64 4}
// NEW-PATH: [[META14]] = !{[[META4]], i64 2, !"short"}
// NEW-PATH: [[TBAA15]] = !{[[META13]], [[META14]], i64 0, i64 2}
// NEW-PATH: [[TBAA16]] = !{[[META17:![0-9]+]], [[META3]], i64 8, i64 4}
// NEW-PATH: [[META17]] = !{[[META4]], i64 24, !"_ZTS7StructB", [[META14]], i64 0, i64 2, [[META13]], i64 4, i64 16, [[META3]], i64 20, i64 4}
// NEW-PATH: [[TBAA18]] = !{[[META17]], [[META14]], i64 4, i64 2}
// NEW-PATH: [[TBAA19]] = !{[[META17]], [[META3]], i64 20, i64 4}
// NEW-PATH: [[TBAA20]] = !{[[META17]], [[META3]], i64 16, i64 4}
// NEW-PATH: [[TBAA21]] = !{[[META22:![0-9]+]], [[META3]], i64 4, i64 4}
// NEW-PATH: [[META22]] = !{[[META4]], i64 8, !"_ZTS7StructS", [[META14]], i64 0, i64 2, [[META3]], i64 4, i64 4}
// NEW-PATH: [[TBAA23]] = !{[[META22]], [[META14]], i64 0, i64 2}
// NEW-PATH: [[TBAA24]] = !{[[META25:![0-9]+]], [[META3]], i64 4, i64 4}
// NEW-PATH: [[META25]] = !{[[META4]], i64 8, !"_ZTS8StructS2", [[META14]], i64 0, i64 2, [[META3]], i64 4, i64 4}
// NEW-PATH: [[TBAA26]] = !{[[META25]], [[META14]], i64 0, i64 2}
// NEW-PATH: [[TBAA27]] = !{[[META28:![0-9]+]], [[META3]], i64 12, i64 4}
// NEW-PATH: [[META28]] = !{[[META4]], i64 32, !"_ZTS7StructC", [[META14]], i64 0, i64 2, [[META17]], i64 4, i64 24, [[META3]], i64 28, i64 4}
// NEW-PATH: [[TBAA29]] = !{[[META30:![0-9]+]], [[META3]], i64 12, i64 4}
// NEW-PATH: [[META30]] = !{[[META4]], i64 36, !"_ZTS7StructD", [[META14]], i64 0, i64 2, [[META17]], i64 4, i64 24, [[META3]], i64 28, i64 4, [[META4]], i64 32, i64 1}
// NEW-PATH: [[TBAA31]] = !{[[META32:![0-9]+]], [[META32]], i64 0, i64 8}
// NEW-PATH: [[META32]] = !{[[META8]], i64 8, !"p1 _ZTS4five"}
// NEW-PATH: [[TBAA33]] = !{[[META34:![0-9]+]], [[META4]], i64 1, i64 1}
// NEW-PATH: [[META34]] = !{[[META4]], i64 3, !"_ZTS4five", [[META4]], i64 0, i64 1, [[META4]], i64 1, i64 1, [[META4]], i64 2, i64 1}
// NEW-PATH: [[TBAA35]] = !{[[META36:![0-9]+]], [[META36]], i64 0, i64 8}
// NEW-PATH: [[META36]] = !{[[META8]], i64 8, !"p1 _ZTS3six"}
// NEW-PATH: [[TBAA37]] = !{[[META38:![0-9]+]], [[META4]], i64 4, i64 1}
// NEW-PATH: [[META38]] = !{[[META4]], i64 6, !"_ZTS3six", [[META4]], i64 0, i64 1, [[META4]], i64 4, i64 1, [[META4]], i64 5, i64 1}
//.
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// NEW-PATH: {{.*}}
// OLD-PATH: {{.*}}
