// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %clang_cc1 -triple x86_64-apple-darwin -O1 -no-struct-path-tbaa -disable-llvm-passes %s -emit-llvm -o - | FileCheck %s
// RUN: %clang_cc1 -triple x86_64-apple-darwin -O1 -disable-llvm-passes %s -emit-llvm -o - | FileCheck %s -check-prefixes=PATH
// RUN: %clang_cc1 -triple x86_64-apple-darwin -O0 -disable-llvm-passes %s -emit-llvm -o - | FileCheck %s -check-prefix=NO-TBAA
// RUN: %clang_cc1 -triple x86_64-apple-darwin -O1 -relaxed-aliasing -disable-llvm-passes %s -emit-llvm -o - | FileCheck %s -check-prefix=NO-TBAA
// Test TBAA metadata generated by front-end.
//

typedef unsigned char uint8_t;
typedef unsigned short uint16_t;
typedef unsigned int uint32_t;
typedef unsigned long long uint64_t;

typedef enum {
  RED_AUTO_32,
  GREEN_AUTO_32,
  BLUE_AUTO_32
} EnumAuto32;

typedef enum {
  RED_AUTO_64,
  GREEN_AUTO_64,
  BLUE_AUTO_64 = 0x100000000ull
} EnumAuto64;

typedef enum : uint16_t {
  RED_16,
  GREEN_16,
  BLUE_16
} Enum16;

typedef enum : uint8_t {
  RED_8,
  GREEN_8,
  BLUE_8
} Enum8;

// CHECK-LABEL: define i32 @g0(
// CHECK-SAME: ptr noundef [[E:%.*]], ptr noundef [[VAL:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[E_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[VAL_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[E]], ptr [[E_ADDR]], align 8, !tbaa [[TBAA6:![0-9]+]]
// CHECK-NEXT:    store ptr [[VAL]], ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA8:![0-9]+]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA8]]
// CHECK-NEXT:    store i32 5, ptr [[TMP0]], align 4, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[E_ADDR]], align 8, !tbaa [[TBAA6]]
// CHECK-NEXT:    store i32 0, ptr [[TMP1]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA8]]
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP2]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret i32 [[TMP3]]
//
// PATH-LABEL: define i32 @g0(
// PATH-SAME: ptr noundef [[E:%.*]], ptr noundef [[VAL:%.*]]) #[[ATTR0:[0-9]+]] {
// PATH-NEXT:  [[ENTRY:.*:]]
// PATH-NEXT:    [[E_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[VAL_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    store ptr [[E]], ptr [[E_ADDR]], align 8, !tbaa [[TBAA6:![0-9]+]]
// PATH-NEXT:    store ptr [[VAL]], ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA8:![0-9]+]]
// PATH-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA8]]
// PATH-NEXT:    store i32 5, ptr [[TMP0]], align 4, !tbaa [[TBAA2:![0-9]+]]
// PATH-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[E_ADDR]], align 8, !tbaa [[TBAA6]]
// PATH-NEXT:    store i32 0, ptr [[TMP1]], align 4, !tbaa [[TBAA2]]
// PATH-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA8]]
// PATH-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP2]], align 4, !tbaa [[TBAA2]]
// PATH-NEXT:    ret i32 [[TMP3]]
//
// NO-TBAA-LABEL: define i32 @g0(
// NO-TBAA-SAME: ptr noundef [[E:%.*]], ptr noundef [[VAL:%.*]]) #[[ATTR0:[0-9]+]] {
// NO-TBAA-NEXT:  [[ENTRY:.*:]]
// NO-TBAA-NEXT:    [[E_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[VAL_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    store ptr [[E]], ptr [[E_ADDR]], align 8
// NO-TBAA-NEXT:    store ptr [[VAL]], ptr [[VAL_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8
// NO-TBAA-NEXT:    store i32 5, ptr [[TMP0]], align 4
// NO-TBAA-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[E_ADDR]], align 8
// NO-TBAA-NEXT:    store i32 0, ptr [[TMP1]], align 4
// NO-TBAA-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP2]], align 4
// NO-TBAA-NEXT:    ret i32 [[TMP3]]
//
uint32_t g0(EnumAuto32 *E, uint32_t *val) {
  *val = 5;
  *E = RED_AUTO_32;
  return *val;
}

// CHECK-LABEL: define i64 @g1(
// CHECK-SAME: ptr noundef [[E:%.*]], ptr noundef [[VAL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[E_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[VAL_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[E]], ptr [[E_ADDR]], align 8, !tbaa [[TBAA6]]
// CHECK-NEXT:    store ptr [[VAL]], ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA10:![0-9]+]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA10]]
// CHECK-NEXT:    store i64 5, ptr [[TMP0]], align 8, !tbaa [[TBAA12:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[E_ADDR]], align 8, !tbaa [[TBAA6]]
// CHECK-NEXT:    store i64 0, ptr [[TMP1]], align 8, !tbaa [[TBAA14:![0-9]+]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP2]], align 8, !tbaa [[TBAA12]]
// CHECK-NEXT:    ret i64 [[TMP3]]
//
// PATH-LABEL: define i64 @g1(
// PATH-SAME: ptr noundef [[E:%.*]], ptr noundef [[VAL:%.*]]) #[[ATTR0]] {
// PATH-NEXT:  [[ENTRY:.*:]]
// PATH-NEXT:    [[E_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[VAL_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    store ptr [[E]], ptr [[E_ADDR]], align 8, !tbaa [[TBAA6]]
// PATH-NEXT:    store ptr [[VAL]], ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA10:![0-9]+]]
// PATH-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA10]]
// PATH-NEXT:    store i64 5, ptr [[TMP0]], align 8, !tbaa [[TBAA12:![0-9]+]]
// PATH-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[E_ADDR]], align 8, !tbaa [[TBAA6]]
// PATH-NEXT:    store i64 0, ptr [[TMP1]], align 8, !tbaa [[TBAA14:![0-9]+]]
// PATH-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA10]]
// PATH-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP2]], align 8, !tbaa [[TBAA12]]
// PATH-NEXT:    ret i64 [[TMP3]]
//
// NO-TBAA-LABEL: define i64 @g1(
// NO-TBAA-SAME: ptr noundef [[E:%.*]], ptr noundef [[VAL:%.*]]) #[[ATTR0]] {
// NO-TBAA-NEXT:  [[ENTRY:.*:]]
// NO-TBAA-NEXT:    [[E_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[VAL_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    store ptr [[E]], ptr [[E_ADDR]], align 8
// NO-TBAA-NEXT:    store ptr [[VAL]], ptr [[VAL_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8
// NO-TBAA-NEXT:    store i64 5, ptr [[TMP0]], align 8
// NO-TBAA-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[E_ADDR]], align 8
// NO-TBAA-NEXT:    store i64 0, ptr [[TMP1]], align 8
// NO-TBAA-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP2]], align 8
// NO-TBAA-NEXT:    ret i64 [[TMP3]]
//
uint64_t g1(EnumAuto64 *E, uint64_t *val) {
  *val = 5;
  *E = RED_AUTO_64;
  return *val;
}

// CHECK-LABEL: define zeroext i16 @g2(
// CHECK-SAME: ptr noundef [[E:%.*]], ptr noundef [[VAL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[E_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[VAL_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[E]], ptr [[E_ADDR]], align 8, !tbaa [[TBAA6]]
// CHECK-NEXT:    store ptr [[VAL]], ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA16:![0-9]+]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA16]]
// CHECK-NEXT:    store i16 5, ptr [[TMP0]], align 2, !tbaa [[TBAA18:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[E_ADDR]], align 8, !tbaa [[TBAA6]]
// CHECK-NEXT:    store i16 0, ptr [[TMP1]], align 2, !tbaa [[TBAA18]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA16]]
// CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP2]], align 2, !tbaa [[TBAA18]]
// CHECK-NEXT:    ret i16 [[TMP3]]
//
// PATH-LABEL: define zeroext i16 @g2(
// PATH-SAME: ptr noundef [[E:%.*]], ptr noundef [[VAL:%.*]]) #[[ATTR0]] {
// PATH-NEXT:  [[ENTRY:.*:]]
// PATH-NEXT:    [[E_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[VAL_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    store ptr [[E]], ptr [[E_ADDR]], align 8, !tbaa [[TBAA6]]
// PATH-NEXT:    store ptr [[VAL]], ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA16:![0-9]+]]
// PATH-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA16]]
// PATH-NEXT:    store i16 5, ptr [[TMP0]], align 2, !tbaa [[TBAA18:![0-9]+]]
// PATH-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[E_ADDR]], align 8, !tbaa [[TBAA6]]
// PATH-NEXT:    store i16 0, ptr [[TMP1]], align 2, !tbaa [[TBAA18]]
// PATH-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA16]]
// PATH-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP2]], align 2, !tbaa [[TBAA18]]
// PATH-NEXT:    ret i16 [[TMP3]]
//
// NO-TBAA-LABEL: define zeroext i16 @g2(
// NO-TBAA-SAME: ptr noundef [[E:%.*]], ptr noundef [[VAL:%.*]]) #[[ATTR0]] {
// NO-TBAA-NEXT:  [[ENTRY:.*:]]
// NO-TBAA-NEXT:    [[E_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[VAL_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    store ptr [[E]], ptr [[E_ADDR]], align 8
// NO-TBAA-NEXT:    store ptr [[VAL]], ptr [[VAL_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8
// NO-TBAA-NEXT:    store i16 5, ptr [[TMP0]], align 2
// NO-TBAA-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[E_ADDR]], align 8
// NO-TBAA-NEXT:    store i16 0, ptr [[TMP1]], align 2
// NO-TBAA-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP2]], align 2
// NO-TBAA-NEXT:    ret i16 [[TMP3]]
//
uint16_t g2(Enum16 *E, uint16_t *val) {
  *val = 5;
  *E = RED_16;
  return *val;
}

// CHECK-LABEL: define zeroext b8 @g3(
// CHECK-SAME: ptr noundef [[E:%.*]], ptr noundef [[VAL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[E_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[VAL_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[E]], ptr [[E_ADDR]], align 8, !tbaa [[TBAA6]]
// CHECK-NEXT:    store ptr [[VAL]], ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA20:![0-9]+]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA20]]
// CHECK-NEXT:    store i8 5, ptr [[TMP0]], align 1, !tbaa [[TBAA22:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[E_ADDR]], align 8, !tbaa [[TBAA6]]
// CHECK-NEXT:    store i8 0, ptr [[TMP1]], align 1, !tbaa [[TBAA22]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA20]]
// CHECK-NEXT:    [[TMP3:%.*]] = load b8, ptr [[TMP2]], align 1, !tbaa [[TBAA22]]
// CHECK-NEXT:    ret b8 [[TMP3]]
//
// PATH-LABEL: define zeroext b8 @g3(
// PATH-SAME: ptr noundef [[E:%.*]], ptr noundef [[VAL:%.*]]) #[[ATTR0]] {
// PATH-NEXT:  [[ENTRY:.*:]]
// PATH-NEXT:    [[E_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    [[VAL_ADDR:%.*]] = alloca ptr, align 8
// PATH-NEXT:    store ptr [[E]], ptr [[E_ADDR]], align 8, !tbaa [[TBAA6]]
// PATH-NEXT:    store ptr [[VAL]], ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA20:![0-9]+]]
// PATH-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA20]]
// PATH-NEXT:    store i8 5, ptr [[TMP0]], align 1, !tbaa [[TBAA22:![0-9]+]]
// PATH-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[E_ADDR]], align 8, !tbaa [[TBAA6]]
// PATH-NEXT:    store i8 0, ptr [[TMP1]], align 1, !tbaa [[TBAA22]]
// PATH-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8, !tbaa [[TBAA20]]
// PATH-NEXT:    [[TMP3:%.*]] = load b8, ptr [[TMP2]], align 1, !tbaa [[TBAA22]]
// PATH-NEXT:    ret b8 [[TMP3]]
//
// NO-TBAA-LABEL: define zeroext b8 @g3(
// NO-TBAA-SAME: ptr noundef [[E:%.*]], ptr noundef [[VAL:%.*]]) #[[ATTR0]] {
// NO-TBAA-NEXT:  [[ENTRY:.*:]]
// NO-TBAA-NEXT:    [[E_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    [[VAL_ADDR:%.*]] = alloca ptr, align 8
// NO-TBAA-NEXT:    store ptr [[E]], ptr [[E_ADDR]], align 8
// NO-TBAA-NEXT:    store ptr [[VAL]], ptr [[VAL_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8
// NO-TBAA-NEXT:    store i8 5, ptr [[TMP0]], align 1
// NO-TBAA-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[E_ADDR]], align 8
// NO-TBAA-NEXT:    store i8 0, ptr [[TMP1]], align 1
// NO-TBAA-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[VAL_ADDR]], align 8
// NO-TBAA-NEXT:    [[TMP3:%.*]] = load b8, ptr [[TMP2]], align 1
// NO-TBAA-NEXT:    ret b8 [[TMP3]]
//
uint8_t g3(Enum8 *E, uint8_t *val) {
  *val = 5;
  *E = RED_8;
  return *val;
}

//.
// CHECK: [[TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// CHECK: [[META3]] = !{!"int", [[META4:![0-9]+]], i64 0}
// CHECK: [[META4]] = !{!"omnipotent char", [[META5:![0-9]+]], i64 0}
// CHECK: [[META5]] = !{!"Simple C/C++ TBAA"}
// CHECK: [[TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
// CHECK: [[META7]] = !{!"any pointer", [[META4]], i64 0}
// CHECK: [[TBAA8]] = !{[[META9:![0-9]+]], [[META9]], i64 0}
// CHECK: [[META9]] = !{!"p1 int", [[META7]], i64 0}
// CHECK: [[TBAA10]] = !{[[META11:![0-9]+]], [[META11]], i64 0}
// CHECK: [[META11]] = !{!"p1 long long", [[META7]], i64 0}
// CHECK: [[TBAA12]] = !{[[META13:![0-9]+]], [[META13]], i64 0}
// CHECK: [[META13]] = !{!"long long", [[META4]], i64 0}
// CHECK: [[TBAA14]] = !{[[META15:![0-9]+]], [[META15]], i64 0}
// CHECK: [[META15]] = !{!"long", [[META4]], i64 0}
// CHECK: [[TBAA16]] = !{[[META17:![0-9]+]], [[META17]], i64 0}
// CHECK: [[META17]] = !{!"p1 short", [[META7]], i64 0}
// CHECK: [[TBAA18]] = !{[[META19:![0-9]+]], [[META19]], i64 0}
// CHECK: [[META19]] = !{!"short", [[META4]], i64 0}
// CHECK: [[TBAA20]] = !{[[META21:![0-9]+]], [[META21]], i64 0}
// CHECK: [[META21]] = !{!"p1 omnipotent char", [[META7]], i64 0}
// CHECK: [[TBAA22]] = !{[[META4]], [[META4]], i64 0}
//.
// PATH: [[TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// PATH: [[META3]] = !{!"int", [[META4:![0-9]+]], i64 0}
// PATH: [[META4]] = !{!"omnipotent char", [[META5:![0-9]+]], i64 0}
// PATH: [[META5]] = !{!"Simple C/C++ TBAA"}
// PATH: [[TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
// PATH: [[META7]] = !{!"any pointer", [[META4]], i64 0}
// PATH: [[TBAA8]] = !{[[META9:![0-9]+]], [[META9]], i64 0}
// PATH: [[META9]] = !{!"p1 int", [[META7]], i64 0}
// PATH: [[TBAA10]] = !{[[META11:![0-9]+]], [[META11]], i64 0}
// PATH: [[META11]] = !{!"p1 long long", [[META7]], i64 0}
// PATH: [[TBAA12]] = !{[[META13:![0-9]+]], [[META13]], i64 0}
// PATH: [[META13]] = !{!"long long", [[META4]], i64 0}
// PATH: [[TBAA14]] = !{[[META15:![0-9]+]], [[META15]], i64 0}
// PATH: [[META15]] = !{!"long", [[META4]], i64 0}
// PATH: [[TBAA16]] = !{[[META17:![0-9]+]], [[META17]], i64 0}
// PATH: [[META17]] = !{!"p1 short", [[META7]], i64 0}
// PATH: [[TBAA18]] = !{[[META19:![0-9]+]], [[META19]], i64 0}
// PATH: [[META19]] = !{!"short", [[META4]], i64 0}
// PATH: [[TBAA20]] = !{[[META21:![0-9]+]], [[META21]], i64 0}
// PATH: [[META21]] = !{!"p1 omnipotent char", [[META7]], i64 0}
// PATH: [[TBAA22]] = !{[[META4]], [[META4]], i64 0}
//.
